### ISSUE TITLE
Commission an official background image

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#141]

**Comment by platipo** [comment]
I created a draft using:
- rust logo [CC-BY](https://github.com/rust-lang/rust/issues/11562)
- wayland logo [MIT](https://cgit.freedesktop.org/wayland/wayland/tree/data/wayland.svg?id=5dfe299b91f2f2e7c8fe460ac08df1935e3c73d5) (I'm confused about the licence becasue [dir](https://cgit.freedesktop.org/wayland/wayland/tree/data/COPYING?id=5dfe299b91f2f2e7c8fe460ac08df1935e3c73d5) is CC but file seems MIT)
![way-cooler](https://user-images.githubusercontent.com/22260641/28245986-620abc44-6a12-11e7-82cc-88d6bd4c4262.png)
Your comments and suggestions would be greatly appreciated.

**Comment by Timidger** [comment]
@platipo 

Thanks for the background draft! This is one of these issues that I cannot do by myself because I'm decidedly not an artist. 

I like how simple it is, just combining two logos together is simple but effective. And I like how you repurposed the Wayland logo to have (what it looks like at least) the blue color we use in the logo. 

I don't like how generic it is though. There are already a lot of Wayland window managers written in Rust (eg Fireplace) so it would be hard to understand the this is the default background for Way Cooler specifically. 

As well, I've tried to not market Way Cooler as a Rust window manager necessarily. It's a cool implementation detail, and is the reason it doesn't segfault and allows me to write features relatively quickly, but it's not the main focus like it is in Fireplace. The main way you extend Fireplace is with Rust, the way you extend Way Cooler is with Lua and D-Bus clients. This means from the user's perspective, they don't need to know it's made with Rust (unlike in Fireplace) and so I don't think it should be prominent in the background. 

Perhaps we could do something like this: remove the Rust background, and write out the rest of the words "Way Cooler" using the same style as the Wayland logo. We can have the "W" be exactly like the standard logo (color and everything) and the rest of the words can be colored like in the logo (eg blue "Way", purple "Cooler"). 

Again, I'm not a graphical designer. The only thing I know is that I want Way Cooler (and thus the background and logo) to be distinctly about the window manager and only tangentially reference the technologies that enable it. So take my suggestions as spit balls of what I think I want.

If you think there's a better way to represent what I want, or even that I should represent Way Cooler in a different way, feel free to tell me I'm wrong :-).

**Comment by platipo** [comment]
Wow, I really appreciated your feedback! I tried to create a less generic logo from Rust and Wayland by coloring it with way-cooler colors, but I see that you pointed out what I was afraid of: beeing too generic, Anyway I like the way you already got a clear concept in mind.

About the "W" of Wayland style, I thought about writng "Way Cooler", but for the moment the idea is out of my competence and I think it may appear too flat (I will give it a shot anyway in future attempts).

Do you have higher resolution [logo](https://avatars6.githubusercontent.com/u/10932466?v=4&s=200) or may I reproduce it and then scale it?

**Comment by Timidger** [comment]
I don't think I have a higher resolution version of the logo unfortunately. I asked the artist if he does, but I think it's simple enough you can just scale it up so go ahead and do that.

**Comment by platipo** [comment]
Unfortunately it seems that the logo has some depth but it's too small to say if it's intentional or a jpeg compression bias.
I can reproduce it, but I'm not sure of original artist intentions. Shall I make a "material" copy?

**Comment by Timidger** [comment]
I can get you a higher resolution one tomorrow, but yeah the depth is not an compression artifact it was intentional.

**Comment by platipo** [comment]
In the meanwhile ![new draft](https://user-images.githubusercontent.com/22260641/28251859-7a7bafee-6a86-11e7-96ea-c73f1862abbf.png)

**Comment by Timidger** [comment]
Oh wow that looks great! I'll be sure to send you the high resolution logo tomorrow, would love to see more variations of this to see what looks the best. But that already looks way cooler than anything I could make (pun intended)

**Comment by platipo** [comment]
Keeping in mind that it's a draft and that the logo is low res
![back-2](https://user-images.githubusercontent.com/22260641/28263055-b9f08ec4-6ae5-11e7-94f6-b59342fd3639.png)

**Comment by Timidger** [comment]
More of a fan of the other one you posted, though I've never particularly liked tiled backgrounds. Though I think it would be nice to provide one. I think the repeating words "Way Cooler" is a little distracting / annoying, and would be more likely to annoy me than anything else.

Don't have any insight on how to improve that (except to change what's tiled, e.g something other than "Way Cooler" repeated), though I do like the logo featured prominently in the center there. It looks better than I thought blown up, even considering the fact you don't have the original (I contacted the artist, he will be posting it here later, he ran into some issues where he couldn't find it so he'll remake it from scratch).

**Comment by Timidger** [comment]
Also, as an implementation explanation, my plan is for the official background(s) to be compiled into `way-cooler-bg` and, if you don't specify a background, will default to these by default (and the `init.lua` will change accordingly to not specify a background so that these are loaded by default)

**Comment by Timidger** [comment]
Sorry for the delay in uploading the high-def version of the logo, it should be up by tomorrow.

**Comment by Timidger** [comment]
Here's the PNG of the updated logo, if anyone needs an svg just ask and I can maybe provide it
![20205832_1407417012658848_1288010692_o](https://user-images.githubusercontent.com/3515754/28487709-943fa124-6e4b-11e7-9908-e19356ef7c08.png)

**Comment by platipo** [comment]
[![back-3.png](https://s2.postimg.org/h8wexajll/back-3.png)](https://postimg.org/image/f4c1w7hyt/)

**Comment by Timidger** [comment]
Excellent, nice job with tiling the logo. It wasn't exactly designed to be mirrored next to itself, but you made it work surprisingly well.

These look great, I'll add them as defaults to way-cooler-bg (so that they show up in default installations of Way Cooler) and release it along with 0.7.

Thanks again for doing this.

**Comment by platipo** [comment]
[![way-cooler-wall4a.png](https://s11.postimg.org/k05djyn5v/way-cooler-wall4a.png)](https://s11.postimg.org/k05djyn5v/way-cooler-wall4a.png)
[![way-cooler-wall4b.png](https://s11.postimg.org/a44akbhdv/way-cooler-wall4b.png)](https://s11.postimg.org/a44akbhdv/way-cooler-wall4b.png)

**Comment by platipo** [comment]
[![way-cooler-wall5.png](https://s29.postimg.org/a39u91xwn/way-cooler-wall5.png)](https://postimg.org/image/uneo7jdnn/)

**Comment by platipo** [comment]
[![way-cooler-wall5.png](https://s3.postimg.org/yaa388xkj/way-cooler-wall5.png)](https://postimg.org/image/5kn7bltkf/)

**Comment by platipo** [comment]
![way-cooler-wall5big](https://user-images.githubusercontent.com/22260641/29455066-fa878fbc-840f-11e7-81c3-03063c3a5521.png)

**Comment by Timidger** [comment]
Not as big of a fan of those last two. I think they look interesting, but I want to go for the more abstract look since it complements the logo well.
