### ISSUE TITLE
Add hide cursor command

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#162]
Programs like [unclutter](https://wiki.archlinux.org/index.php/Unclutter) do not work under Wayland since they rely on clever X tricks that would not work without compositor support under Way Cooler.

As an alternative, lets add an explicit command that will move the cursor out of sight (outside of the bounds of the active outputs, if possible). If there is any movement, Way Cooler will put the mouse back where it was before the command was issued, effectively making it act like it does in unclutter.

**Comment by oblitum** [comment]
I've just written this and I'm happily making use:

- https://gitlab.com/interception/linux/plugins/hideaway

**Comment by Timidger** [comment]
Oh cool! Does it talk to libinput directly?

**Comment by oblitum** [comment]
Yep!
