### ISSUE TITLE
Weston-terminal without borders

### ISSUE THREAD

**Issue by pete3215** [way-cooler/way-cooler#247]
Is there any way to get the weston-terminal to work without border decorations?
It really looks awful in a tiling window manager and I would really like to use a native wayland terminal

**Comment by Timidger** [comment]
That's going to be some weston specific option that may or may not exist. I am unaware if it's possible, I suggest pinging the weston devs about the. 

If you want to use a native Wayland terminal, I suggest looking into others (such as Alacritty and termite). They might be more production ready than weston terminal and potentially more customizable.

**Comment by pete3215** [comment]
When using termite, there is still a border/panel at the top.
On other window mangers there is no such panel, therefore I suspect way-cooler might be responsible.
Is there any option I can try to get rid of this?

**Comment by pete3215** [comment]
Just noticed that other applications have the same issue, seems to be connected to gtk3 apps.
This does not seem to be an issue with other window managers though.
Most of these applications do not have a border/panel when started on awesome.

weston seems to have the same issue, so maybe this is related to wayland or how gtk3 handles the wayland protocol.

**Comment by Timidger** [comment]
This is probably to do with how gtk treats Wayland (e.g it automatically draws client side borders).

See [this wiki post in sway](https://github.com/SirCmpwn/sway/wiki#disabling-client-side-gtk3-decorations) for how to disable it for all gtk3 apps.
