### ISSUE TITLE
Nix package available

### ISSUE THREAD

**Issue by miltador** [way-cooler/way-cooler#281]
Just wanted to mention that I've written `way-cooler` nix package [definition](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/window-managers/way-cooler/default.nix). So it is now available to NixOS users and those who use Nix package manager.

**Comment by Timidger** [comment]
Hey that's sweet, thanks for doing that. I'll add that to the README. However, I'm afraid I haven't used nix before so I wouldn't know if there are any special instructions I have to say. Feel free to send a patch clarifying the wording if necessary.

**Comment by Timidger** [comment]
Oh, also is there some way I can notify/update the package when a new version of Way Cooler comes out? I have access to the AUR package, and I know how to update it and I would like to make sure they can stay in sync.

**Comment by miltador** [comment]
@Timidger, thanks for adding info to README. There is no special instructions, it installs just like any other application.

For new versions:
Short answer: the easiest way I see for you is to open a new issue at [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs) repository and mention package maintainers, currently it's me.

The reason behind that is the way how nix packages are defined, it requires a accumulated `sha256` checksum of all it's Cargo dependencies. In NixOS to calculate it, you just make a build of package with fake checksum and system will calculate new one for you. I don't know how one could calculate in on his own without using `Nix` package manager.

**Comment by Timidger** [comment]
Ok, we'll cross that bridge when we come to it (next version will be 0.6.0, if it wasn't obvious from the milestones on the github page). When I release it I'll open an issue/PR in that repo and @mention you.
