### ISSUE TITLE
Fails to build due to linker not being able to find the wlc SO

### ISSUE THREAD

**Issue by christianboehmeatcloudandheatdotcom** [way-cooler/way-cooler#288]
A `cargo install way-cooler` (with `HEAD` at `bdbcd0bc5ab2a37dc3adaf7145c731fbe48d5bef`) fails with
the linker complaining `/usr/bin/ld: cannot find -lwlc`.  This is because `wlc` lives in a "non-standard"
location over here, like many other pieces of software.

Turns out that `rustwlc-0.6.2` does not ask `pkg-config` at all for where `wlc` can be found, like e.g.
`cairo-sys-rs-0.3.3` does for `cairo`.  Please add support for `pkg-config` for `rustwlc`.  It's probably
a good idea to do this for all _Rust_ wrapper libraries.

**Comment by Timidger** [comment]
Hey thanks for the heads up. I don't have time this week to look into and fix that, but feel free to submit a patch to `rust-wlc` and I'll happily merge it.

**Comment by christianboehmeatcloudandheatdotcom** [comment]
First off, thanks for the quick reply and, of course, bringing `way-cooler` to life! Looking forward to play
with it and move away from _X_ over to _Wayland_.

I'll see what I can do with `rust-wlc`, as it looks like the problem lies solely in there.

**Comment by Sh4d1** [comment]
Hey :) Any update on the issue ? I got the same : 

Compiling on VoidLinux
`error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/patrik/.rustup/toolchains/stable-x86_64-unkn
own-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/way_cooler-da2f
3731258fade6.0.o" "-o" "/tmp/cargo-install.5VEg97AISSgO/release/deps/way_cooler-da2f3731258fade6" "-Wl,--gc-sections"
 "-pie" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/cargo-install.5VEg97AISSgO/release/deps" "-L" "/usr/lib" "-L" "/usr/lib
" "-L" "/usr/lib" "-L" "/usr/lib" "-L" "/tmp/cargo-install.5VEg97AISSgO/release/build/lua52-sys-e5746a2581c5903b/out"
 "-L" "/home/patrik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl
,-Bstatic" "/tmp/cargo-install.5VEg97AISSgO/release/deps/librustwlc-603615e9f6d92910.rlib" "/tmp/cargo-install.5VEg97
AISSgO/release/deps/libhlua-04ef9ad2b783ee62.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libjson_macro-8a714d
5c4aa94a9b.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libdbus_macros-b8d9c001b50d6a03.rlib" "/tmp/cargo-inst
all.5VEg97AISSgO/release/deps/libwayland_sys-8e4b4dca46459240.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/lib
getopts-13c1056d1aaf1cf1.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libpetgraph-471d06583d441202.rlib" "/tmp
/cargo-install.5VEg97AISSgO/release/deps/libfixedbitset-4c7f0763b8bce946.rlib" "/tmp/cargo-install.5VEg97AISSgO/relea
se/deps/libuuid-867915a4c46cd3ec.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/librustc_serialize-9724b3bb92070
153.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/librand-695c6498463562d2.rlib" "/tmp/cargo-install.5VEg97AISS
gO/release/deps/libcairo-aa7314471cb59391.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libcairo_sys-7bf593585c
a48c33.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libglib-2b269a20a7ce5a8d.rlib" "/tmp/cargo-install.5VEg97A
ISSgO/release/deps/libgobject_sys-c1adfa1f9205f40e.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libbitflags-00
81ea926e22252a.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libwayland_server-2ce5f28b56d503b3.rlib" "/tmp/car
go-install.5VEg97AISSgO/release/deps/libnix-f3e04e7352331f48.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libb
itflags-f04a350017ff37cf.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libenv_logger-e86e622359cc2e43.rlib" "/t
mp/cargo-install.5VEg97AISSgO/release/deps/libregex-13b08a0a7d8327c5.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/d
eps/libutf8_ranges-ec078987c8e86074.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libthread_local-93f27e0aae2d3
926.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libthread_id-139ae7ca43e25479.rlib" "/tmp/cargo-install.5VEg9
7AISSgO/release/deps/libaho_corasick-96273573f06d3549.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/liblog-5da5
b1aa034b348f.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libmemchr-aed5ac89b50cf36c.rlib" "/tmp/cargo-install
.5VEg97AISSgO/release/deps/libregex_syntax-f42a4ec18be03753.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/liblu
a52_sys-32f64e802ebd3372.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libnix-ed2a7d3482321c1a.rlib" "/tmp/carg
o-install.5VEg97AISSgO/release/deps/libcfg_if-79b49584c98657bd.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/li
bbitflags-7fa93fb0ed8de7af.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libvoid-06ca3f8295b8184f.rlib" "/tmp/c
argo-install.5VEg97AISSgO/release/deps/libordermap-7a7923d1ed67a821.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/de
ps/libdbus-013cadfd140d38bf.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libc_vec-2b1fc1d9cdfa5bcf.rlib" "/tmp
/cargo-install.5VEg97AISSgO/release/deps/libglib_sys-4170481542981c27.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/
deps/libbitflags-de593ad175e9f2d4.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/libwayland_sys-c65d87607c0830ed
.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/liblibc-09a9e8ddf4dbba25.rlib" "/tmp/cargo-install.5VEg97AISSgO/
release/deps/libdlib-fb2b1264798880a3.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/liblibloading-df5012668b8e0
2fd.rlib" "/tmp/cargo-install.5VEg97AISSgO/release/deps/liblazy_static-976016df0a45293a.rlib" "/home/patrik/.rustup/t
oolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-35ad9950c7e5074b.rlib" "/ho
me/patrik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind
-fb44afc024bbc636.rlib" "/home/patrik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-l
inux-gnu/lib/libunwind-14b8f3202acdad6a.rlib" "/home/patrik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/ru
stlib/x86_64-unknown-linux-gnu/lib/librand-20a50a22d4c2b1e9.rlib" "/home/patrik/.rustup/toolchains/stable-x86_64-unkn
own-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-b479831207997444.rlib" "/home/patrik/.rustup/to
olchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-10b591f1a68dd370.rlib" "/h
ome/patrik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemal
loc-28913dc5a1e63cd7.rlib" "/home/patrik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknow
n-linux-gnu/lib/liblibc-6ecacccb5bdc4911.rlib" "/home/patrik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/r
ustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-f4f0ae88f5ad8ad4.rlib" "/home/patrik/.rustup/toolchains/stable-x86
_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-bfaa82017ca17cb2.rlib" "/home/patrik/.rustup/t
oolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-863b57a66ba6c
3e1.rlib" "-Wl,-Bdynamic" "-l" "wlc" "-l" "wlc" "-l" "wlc" "-l" "wlc" "-l" "xkbcommon" "-l" "wlc" "-l" "wlc" "-l" "ca
iro" "-l" "gobject-2.0" "-l" "glib-2.0" "-l" "dbus-1" "-l" "glib-2.0" "-l" "util" "-l" "dl" "-l" "dl" "-l" "rt" "-l"
"pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util"
  = note: /usr/bin/ld: cannot find -lwlc
          /usr/bin/ld: cannot find -lwlc
          /usr/bin/ld: cannot find -lwlc
          /usr/bin/ld: cannot find -lwlc
          /usr/bin/ld: cannot find -lxkbcommon
          /usr/bin/ld: cannot find -lwlc
          /usr/bin/ld: cannot find -lwlc
          collect2: error: ld returned 1 exit status
`

**Comment by Timidger** [comment]
Sorry about this problem cropping up again. If anyone wants to fix the issue (it's present in rust-wlc really, not in way-cooler), feel free to. However, I'm not going to bother to fix it since we will eventually switch to wlroots and I'll be sure to make the wrapper lib properly when I do (e.g hopefully no linker issues)

**Comment by Timidger** [comment]
This will no longer be an issue in wlroots because we will statically link to it by default.
