### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by rawkode** [way-cooler/way-cooler#292]
Hi,

I've playing around with this and I'm liking it. I was just wondering how I set the screen resolution?

**Comment by Timidger** [comment]
Hey there!

We don't currently expose any way to set the resolution. If you want to try adding the feature yourself, [this wlc method](https://github.com/Cloudef/wlc/blob/master/include/wlc/wlc.h#L333) looks like a good way to start. The steps to do so would be pretty simple:
1) Make sure the method is defined `rust-wlc`, and wrapped in a function that ensures it's safe to call (e.g, passes a valid reference to to a `Size` struct)
2) Add a command in the [tree code](https://github.com/way-cooler/way-cooler/blob/master/src/layout/commands.rs) that takes a new resolution and updates both the `WlcOutput` and the `Container::Output` in the tree. Will probably want to add a method in `core/tree.rs` and `core/container.rs` so it's easier to set an `Output` container's resolution
3) Expose the resolution option through the configuration file (either add it to an existing category, or add another one [here](https://github.com/way-cooler/way-cooler/blob/master/src/registry/mod.rs#L41))

I'll probably fix this later myself, but I'm a bit busy right now with exams. Feel free to tackle this yourself and submit a PR, if you need any help just post on this issue or in our [gitter chat](https://gitter.im/Immington-Industries/way-cooler)

**Comment by rawkode** [comment]
Thanks for the detailed instructions, @Timidger.

I've never written any Rust, but I'll see how far I can get!

**Comment by Timidger** [comment]
This will be supported in wlroots
