### ISSUE TITLE
Startup fails without explanation when $XDG_RUNTIME_DIR doesn't exist

### ISSUE THREAD

**Issue by kazcw** [way-cooler/way-cooler#294]
To reproduce:
- set XDG_RUNTIME_DIR to any directory that doesn't exist
- launch way-cooler
Result: way-cooler shows some DEBUG messages enumerating the env, then exits with status 1 without any error message.

**Comment by Timidger** [comment]
Ah, that would probably be due to internal Wayland details (I believe that's where it places its socket for IPC). I haven't tested against this, but it probably fails during wlc init. Should be trivial to check if that exists, and printing an error and exiting early if necessary.
