### ISSUE TITLE
RFC: Tiling windows from Lua (including i3 tiling)

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#324]
Currently, Way Cooler does all of its tiling "in house". That is, the compositor is responsible for where containers are drawn on the screen. This has worked so far, but in order to make Way Cooler more flexible, less of an i3 clone, and more true to its core idea of being a spiritual successor to awesomewm, I am going to move the current i3 tiling algorithms from Way Cooler itself into Lua.

From a user perspective, nothing will change except you'll get some new lines of boiler plate in your `init.lua` to this effect:

```lua
-- will probably just be injected in,
-- but in the future I want this to work
require "tiling"

-- layouts is a list of dictionaries, that are essentially like this:
-- {"Horizontal": <implementation details of horizontal tiling>}
-- for more info on implementation details, see later in this issue
way_cooler.layouts = [
  tiling.i3.horizontal,
  tiling.i3.vertical,
  tiling.i3.tabbed,
  -- We don't like stacked, so we comment it out.
  -- You can enable or disable any of these.
  -- tiling.i3.stacked
]
```

The way tiling from Lua will work is like this:

You define your layout, lets call it "MyLayout". You can create it in a bare lua table, or you can nest it in a variable like I did above with the i3 style ones. We'll do it with just a table:

```lua
my_layout = {
  -- The name of the layout.
  -- This is displayed on the borders of the container,
  -- and distinguishes it so that it can be selected by commands.
  "My Layout": {
    -- This is one of two callbacks,
    -- this first one define how to do "movement" and "resizing"
    -- of sub containers within the container when given a direction,
    -- and the UUID of one of the sub containers we are focused on.
    -- We return the UUID of the container that we should perform that
    -- action on (e.g either focusing on it, or resizing it).
    --
    -- e.g for horizontal, anything that's "left" or "right" and for UUIDs
    -- of a container not on the end will result in us returning either
    -- the container immediately to the left or right of it.
    function(direction, focused_id)
      if direction == "left" || direction == "right" then
        -- get the container we want to focused on
        return focused_id
      else
        -- get the ancestor container that's up or down of focused_id
        -- we will provide methods to make this easier
        return focused_id
      end
    end,
    
    -- finally, we have the main layout method, which takes in a list
    -- of containers (which are tables with various attributes).
    --
    -- One of these attributes is geometry, which we are free to modify.
    -- We then return the array of updated containers, which will
    -- be updated internally by Way Cooler.
    function(containers)
      -- This is a stupid layout, we don't touch them at all.
      -- The only thing we do is ensure they are all floating,
      -- so that the user can still move and resize them freely.
      --
      -- Note that this is _exactly_ like the free floating layout
      -- for awesomewm
      for _, container in ipairs(containers) do
        container.floating = true
      end
      return containers
    end
  }
}
    
    
-- Just like before, we pass it to way_cooler
-- We just have the one layout, this overwrites anything
-- that was there before.
way_cooler.layouts = [ my_layout ]
```

Inherently, this is callback based. Way Cooler simply provides a very nice framework for managing the layout tree that the tiling code can use, and for ensuring that boring things such as focusing on the last container, floating containers, full screen containers, and border color updates are handled appropriately.

The one bit of boiler plate I'm not happy with is the first callback, the one that gets the container to modify. I'll look into seeing if I can have it elided, as it's a pretty low level, boring detail to consider.

If anyone has any thoughts on this, especially people who used awesome before and defined their own layouts, I would love to hear them. This is the design that makes the most sense to me, but it's possible it's inflexible in some way that I did not consider.

**Comment by matthiasbeyer** [comment]
Hi. I'm not involved with this project at all, though I'd like to remind you to keep multi-screen setups in mind! I loved how i3 handled multi-screen setups, although it had quirks. Make sure this is flexible enough to do proper multi-screen handling (for example if I hit a key-combo to move a window to the left, but it is on the left side of the right screen, I want it to move to the right side of the left screen.... just as an example).

Besides: I'd love scriptability when trying out way-cooler! :heart:

**Comment by Timidger** [comment]
@matthiasbeyer 

Thanks for the insight on handling that corner case! 

I've been thinking about a lot of the future of Way Cooler recently, and the amount of time and effort I'm throwing away by not attempting to use the Lua libraries from awesome. 

My rough plan going forward is to try to target awesome libraries so that Way Cooler can function as a drop in replacement for Awesome. This would invalidate this RFC (since they have a much better mechanism in place for this). 

I'll leave this open though until I finalize my thoughts on the matter.
