### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Applemann** [way-cooler/way-cooler#326]
Hello, I am trying install way-cooler, but command:

```
$ curl https://way-cooler.github.io/way-cooler-release-i3-default.sh -sSLf | sh -s  way-cooler-bg  wc-grab  wc-lock
```

Return error:
`sh: 3: Syntax error: "(" unexpected`

I have distribution:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

```

**Comment by Timidger** [comment]
Interesting, just verified it works on my machine. I'm running Arch though, so it's possible I used a fancy feature only available on newer `sh` versions.

Looking around, it looks like I'm using the wrong syntax for functions. I'm using `function name() ...` when I should be using `function name ...`. 

I have pushed that fix to the website, it _should_ work now (make sure to clear your cache before trying again).

**Comment by Applemann** [comment]
@Timidger Now it get me: `sh: 3: function: not found`
I downloaded the script:
`curl https://way-cooler.github.io/way-cooler-release-i3-default.sh -sSLf > cooler.sh`

fixed line 3: `function cleanup () {`

And run with bash because with sh it not work:
```
>> bash cooler.sh way-cooler-bg wc-grab wc-lock
Fetching second stage install script...
Fetching way-cooler...
Fetching way-cooler-bg...
Fetching wc-grab...
Fetching wc-lock...
Fetching wc-lock-pam...
Starting second stage
./install.sh: 2: set: Illegal option -o pipefail
```
 So what is the option -o pipefail?? 
I didn't look that yet.

Can you install Ubuntu 16.4. LTS on virtualbox for example and debug it there??

**Comment by Timidger** [comment]
Oh I know why that happens, my bad. Sh is symlinked to bash on my machine, I shouldn't have assumed it was. I fix this later (by specifying to use bash in the script, not ah)

**Comment by Applemann** [comment]
@Timidger ok so How can I install the way-cooler now??

**Comment by Timidger** [comment]
I have pushed those changes already. Feel free to try it again. 

If it continues to not work, you can also build it from source. If you want all the programs though (wc-grab, wc-lock, etc) you'll need to build them all from source as well (they are in separate repos under this organization)

**Comment by Applemann** [comment]
@Timidger it not works again.. Whare is some tutorial how build and install it from source??
I am new in Rust..

**Comment by Timidger** [comment]
Fixed with the latest push to github pages repo (tested myself)
