### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by platipo** [way-cooler/way-cooler#335]
I loved [online documentation pages](http://way-cooler.org/), but I still stumbled configuring way-cooler because it's missing man page.
Maybe it's just me but for example I didn't find a way to get screenshot working  even though I'm aware of the work done in #278. (Sorted out: I'm using `scrot` instead of ` way-cooler-grab` 🤦‍)
Anyway in my opinion man page lack pushes away beginners from this awesome WM.

**Comment by Timidger** [comment]
Thanks for the insight! I've been meaning to write man pages, especially ones that can be generated from eg markdown and hosted on the site as well (so you can have man pages for offline documentation, and the same documentation on the website). 

Unfortunately I don't really have the time for that right now, especially as I don't know the man page format. I'm pretty busy right now trying to add am awesomeWM compatibility layer to Way Cooler. 

If you, or anyone else, is willing to write documentation though I will happily assist on any questions you have and any pull requests you open to include it. Feel free to ping me on the gitter chat if you need any help.

**Comment by AdminXVII** [comment]
Do you find the man pages satisfactory? If not, what would you have more detailed?

**Comment by Timidger** [comment]
Ah just didn't realize this wasn't closed automatically. 

Feel free to add a "fixes #<issue_number>" in your future PRs that actually fix said issue.

**Comment by AdminXVII** [comment]
I did, I think you overlooked it? It is in the PR's description
