### ISSUE TITLE
Build failing for both way-cooler and way-cooler-git

### ISSUE THREAD

**Issue by SampsonCrowley** [way-cooler/way-cooler#339]
Brand new Arch build, apacman install returns: 

```sh
error: failed to load source for a dependency on `nix` #the package in backticks changes every time

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index
```

**Comment by Timidger** [comment]
Are you sure you're running an up to date version of Cargo, and you are not behind eg a firewall that will block access? 

Can you try building it from source directly and see if that works?

**Comment by SampsonCrowley** [comment]
I am running the must up to date version of cargo available on Pacman, and firewalls are not an issue

i will try it from source when I get a chance and update with the results

**Comment by Timidger** [comment]
Are you sure it's not [this issue](https://github.com/rust-lang/cargo/issues/2605)? If not, when you build from source please include the full output

**Comment by Timidger** [comment]
Closing this as I cannot reproduce
