### ISSUE TITLE
Switch to last workspace

### ISSUE THREAD

**Issue by platipo** [way-cooler/way-cooler#340]
A killing feature from other WMs (like `dwm`, `bspwm`, or even [`i3`](https://github.com/i3/i3/issues/528)) that is missing on wc is the ability to switch to last workspace.

**Comment by Timidger** [comment]
You're right, that would be a nice feature. It can be added, but it would require some changes (documenting here for when I return to this, or for others to tackle):

1) Need to make sure the active number (e.g the value in the `Path` we store between nodes in the layout tree) is updated properly for the children of the output.
2) If we want this to work across outputs, we need to have the numbers be unique across all outputs, which would made the implementation a bit tricky and make it different from how it works in other parts of the tree
3) Add a keybinding that automatically finds the next container to focus on (e.g the lowest active number workspace that isn't `0`) and focus on it using `switch_to_workspace`.
