### ISSUE TITLE
Segfault when using invalid drm device

### ISSUE THREAD

**Issue by versusvoid** [way-cooler/way-cooler#346]
I have two GPUs. Simply running `way-cooler` result in segfault:
```
Program terminated with signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  0x00007f97899ec8a7 in wl_list_remove () at /usr/lib/libwayland-server.so.0
#1  0x00007f978b83ae99 in  () at /usr/lib/libwlc.so.0
#2  0x00007f978b81ca47 in  () at /usr/lib/libwlc.so.0
#3  0x00007f978b83852c in  () at /usr/lib/libwlc.so.0
#4  0x00007f978b835bfb in  () at /usr/lib/libwlc.so.0
#5  0x000055bffd19a554 in way_cooler::main () at src/main.rs:194
```

`WLC_DRM_DEVICE=card1 way-cooler` works fine (thanks [sway](https://github.com/SirCmpwn/sway/wiki#i-have-a-multi-gpu-setup-like-intelnvidia-or-intelamd-and-sway-does-not-start) for pointing it out).

**Comment by Timidger** [comment]
Sorry for not making that clearer, we'll be sure to document that on the website later (probably under an FAQ section). 

Since we'll be switching to wlroots, we'll hold off on it though since it'll probably be fixed by the time we use that (as the bug is in how wlc chooses the video card).

**Comment by Timidger** [comment]
Going to go ahead and close this since this can be either fixed or better documented when we switch to wlroots
