### ISSUE TITLE
Can't run way-cooler

### ISSUE THREAD

**Issue by NickeZ** [way-cooler/way-cooler#360]
Hey,

Cool project! I'm trying to run it but I'm failing. Where are the instructions on how to run it?

I'm using Ubuntu 16.04 LTS.

I'm attaching a log from running it.
[way.txt](https://github.com/way-cooler/way-cooler/files/1203447/way.txt)

**Comment by NickeZ** [comment]
Also, are you not checking `isatty` before you output or should I create a log in some other way? I did `way-cooler 2>&1 | tee way.txt`

**Comment by NickeZ** [comment]
Running it in i3wm I get segfault after the following output:
[way2.txt](https://github.com/way-cooler/way-cooler/files/1203453/way2.txt)

**Comment by Timidger** [comment]
Hey there.

Doing that way to log way cooler is fine, those characters that are escaped are color codes so that it's easier to see in e.g less. It looks a little strange if you try to view it directly in an editor (and since the program isn't made in a unixy way, e.g the output isn't designed to be piped to a program, I think this is an ok design decision personally).

Can you provide a coredump file or a backtrace at the segfault? Would help diagnose where the issue is. Does it segfault in the same place if you run it in a tty as well as embedded in x11, or is it different?

**Comment by NickeZ** [comment]
It doesn't segfault on tty. In the log it looks like it is shutting down instead of running. Do I need to do anything else than running `./target/*/way-cooler`?

Here is a backtrace from when it segfaults in X:

```
(gdb) bt
#0  0x00007ffff5d6fac7 in wl_list_remove () from /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#1  0x00007ffff7bb8741 in wlc_xwm_selection_release (xwm=<optimized out>) at /home/niklas/git/wlc/src/xwayland/selection.c:460
#2  0x00007ffff7bb76e6 in wlc_xwm_release (xwm=xwm@entry=0x7ffff7dd53b0 <wlc+2544>) at /home/niklas/git/wlc/src/xwayland/xwm.c:853
#3  0x00007ffff7b999f3 in xwayland_event (listener=0x7ffff7dd5c00 <wlc+4672>, data=<optimized out>) at /home/niklas/git/wlc/src/compositor/compositor.c:318
#4  0x00007ffff7bb4bbc in wl_signal_emit (data=0x7fffffffcd9f, signal=0x7ffff7dd5e00 <wlc+5184>) at /usr/include/wayland-server-core.h:357
#5  wlc_xwayland_terminate () at /home/niklas/git/wlc/src/xwayland/xwayland.c:225
#6  0x00007ffff7bb54f5 in destroy_event (listener=<optimized out>, data=<optimized out>) at /home/niklas/git/wlc/src/xwayland/xwayland.c:209
#7  0x00007ffff5d6b17c in wl_client_destroy () from /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#8  0x00007ffff5d6b298 in ?? () from /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#9  0x00007ffff5d6d4b2 in wl_event_loop_dispatch () from /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#10 0x00007ffff5d6b955 in wl_display_run () from /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#11 0x00007ffff7bb274c in wlc_run () at /home/niklas/git/wlc/src/wlc.c:260
#12 0x0000555555837c89 in rustwlc::run_wlc () at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/rustwlc-0.6.2/src/lib.rs:235
#13 0x000055555580f37b in way_cooler::main () at src/main.rs:215
#14 0x0000555555a93d4d in panic_unwind::__rust_maybe_catch_panic () at /checkout/src/libpanic_unwind/lib.rs:98
#15 0x0000555555a8d4ac in std::panicking::try<(),closure> () at /checkout/src/libstd/panicking.rs:458
#16 std::panic::catch_unwind<closure,()> () at /checkout/src/libstd/panic.rs:361
#17 std::rt::lang_start () at /checkout/src/libstd/rt.rs:61
#18 0x000055555582bb83 in main ()
```

**Comment by Timidger** [comment]
Hey, sorry for getting back so late. 

Have you tried running sway? If you have an issue with that, it's probably an issue in wlc and not something I can fix (eg if you are running proprietary Nvidia driver on an old wlc version, or multi card setup, or some other bug). 

You shouldn't need to do anything other than run the binary. 

The fact it's failing at wlc startup makes me think it's a wlc / environment issue

**Comment by NickeZ** [comment]
Hey, I'm not sure I will have time to try to run Sway. I also had to remove libwayland/wayland-protocol that I installed through PPA beacuse it was conflicting with other packages. (Seems like the PPA doesn't use the same packaging as Canonical). So I will probably wait with trying out way-cooler again until I've updated my system from Ubuntu 16.04. Feel free to close this issue.

**Comment by Timidger** [comment]
Ok, sorry I couldn't help resolve your issue :-(
