### ISSUE TITLE
Can't open apps, LayoutTree did not have a parent of type Root, did nothing!

### ISSUE THREAD

**Issue by bew** [way-cooler/way-cooler#373]
On startup I have a mauve color background, but I can't open the wayland terminal, nothing shows up (tried in X11, and in VT).

Logs:
- init: https://pastebin.com/i8jBbNkQ
- Alt-Enter: https://pastebin.com/R2JDHNxR
- ^C: https://pastebin.com/bsr9af0H

Thanks

**Comment by Timidger** [comment]
The warning in your title is nothing to worry about, that is an erroneous report that doesn't relate to the issue present in your post body.

The fact the background comes up is a nice start, and the terminal is obviously starting so something else must be the problem...

Are you sure there's no other wm running at the same time (if X11 or another Wayland compositor is running it sometimes steals windows from Way Cooler)?

Have you tried running other apps? E.g dmenu? It might just be an issue with "Wayland terminal".
