### ISSUE TITLE
AwesomeWM: client API

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#387]
These will require dealing with clients, so with wlc that means interacting with `WlcView`. Like the outputs API, this will change when we move to wlroots so don't get dependent on the implementation details of `WlcView`.

The only thing necessary for basic `rc.lua` is `get` though, so this is something we can put off until `rc.lua` starts throwing more errors as we fill in the rest of the API.

## Functions
* [ ] `get`
* [ ] `keys`
* [ ] `isvisible`
* [ ] `geometry`
* [ ] `apply_size_hints`
* [ ] `tags`
* [ ] `kill`
* [ ] `swap`
* [ ] `raise`
* [ ] `lower`
* [ ] `unmanange`
* [ ] `titlebar_top`
* [ ] `titlebar_right`
* [ ] `titlebar_bottom`
* [ ] `titlebar_left`
* [ ] `get_icon`
* [ ] `name`
* [ ] `transient_for`
* [ ] `skip_taskbar`
* [ ] `content`
* [ ] `type_`
* [ ] `class`
* [ ] `instance`
* [ ] `role`
* [ ] `pid`
* [ ] `leader_window`
* [ ] `machine`
* [ ] `icon_name`
* [ ] `screen`
* [ ] `hidden`
* [ ] `minimized`
* [ ] `fullscreen`
* [ ] `modal`
* [ ] `group_window`
* [ ] `maximized`
* [ ] `maximized_horizontal`
* [ ] `maximized_vertical`
* [ ] `icon`
* [ ] `icon_sizes`
* [ ] `ontop`
* [ ] `above`
* [ ] `below`
* [ ] `sticky`
* [ ] `size_hints_honor`
* [ ] `urgent`
* [ ] `size_hints`
* [ ] `focusable`
* [ ] `shape_bounding`
* [ ] `shape_clip`
* [ ] `shape_input`
* [ ] `startup_id`
* [ ] `client_shape_bounding`
* [ ] `client_shape_clip`
* [ ] `first_tag`

**Comment by SolidTux** [comment]
I started experimenting with the `get` function, but I'm not entirely sure, how to get the data into the correct format (the current state is in SolidTux/way-cooler@96caeb3). I use this code to test it:

```lua
local c = client.get()
print(#c)
print()
for x,v in ipairs(c) do
  print(tostring(x) .. " " .. tostring(v))
  print(v.name)
  print(type(v))
end
```

From AwesomeWM I get something like

```
5

1  window/client(AwesomeWM: client AP...): 0x55dca08f9028
AwesomeWM: client API · Issue #387 · way-cooler/way-cooler - Mozilla Firefox
client
2  window/client(Terminal): 0x55dc9f3d5608
Terminal
client
[...]
```

while with Way Cooler it returns

```
2

1 Client: 0x7f404b9fa310
nil
table
2 Client: 0x7f404b9fa310
nil
table
```

How can I get Lua to recognize the data as `client` and not as `table`?

**Comment by Timidger** [comment]
The print function is defined [here](https://github.com/SolidTux/way-cooler/blob/master/src/awesome/client.rs#L41) which is what you need to change to not make it print a pointer.

The type that makes it determine it's a table is more complicated. See [this issue I updated for more information](https://github.com/way-cooler/way-cooler/issues/466). Basically to fix this we would need to change [this allocated code](https://github.com/SolidTux/way-cooler/blob/master/src/awesome/object.rs#L91) to better match [the code found in awesome](https://github.com/awesomeWM/awesome/blob/master/common/luaobject.h#L169).

(Sorry for the information dump on fixing `allocate`. I realize that's a lot and should be dealt with in a separate PR. I plan to get around to it _eventually_ but all of my efforts are focused on [wlroot-rs](https://github.com/swaywm/wlroots-rs) at the moment. If you want to tackle this though feel free to reach out on the [gitter channel](https://gitter.im/way-cooler/way-cooler) and I or @psychon can walk you through what needs to change)

**Comment by SolidTux** [comment]
Sorry for letting you wait so long. Is your description still valid or did something change since then?

**Comment by Timidger** [comment]
Nothing has changed since then, should still be the same.

If you run into issues feel free to reach out on #awesome on OFTC

**Comment by psychon** [comment]
> How can I get Lua to recognize the data as client and not as table?

I think this was already handled in the mean time, but I do not have the time to look into it right now.

**Comment by Timidger** [comment]
psychon is correct, that has been fixed (apologies, I only glanced at the issue and forgot the original problem)
