### ISSUE TITLE
AwesomeWM: drawin API

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#388]
Lowest level API for drawing things in Awesome. This is a dependency for all drawn things, and is the holder of the cairo and pixman contexts.

Interface is basic, but the implementation is a bit tricky since this will actually require interacting with Cairo. If you want to tackle this, talk to me and look at the code under `src/render`

## Functions
- [X] `__call`
- [X] `geometry`

## Properties
- [X] `drawable`
- [ ] `visible`
- [ ] `ontop`
- [ ] `cursor`
- [X] `x`
- [X] `y`
- [X] `width`
- [X] `height`
- [ ] `type`
- [ ] `shape_bounding`
- [ ] `shape_clip`
- [ ] `shape_input`
- [X] `struts`

**Comment by psychon** [comment]
`__call`, `geometry`, `drawable`, `x`, `y`, `width`, `height` and `struts` (missing from the above list) are implemented.

**Comment by Timidger** [comment]
Thanks, updates
