### ISSUE TITLE
AwesomeWM: drawable API

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#389]
## Functions
* [X] `refresh`
* [X] `geometry`

## Properties
- [X] `surface`

**Comment by Timidger** [comment]
Blocked by https://github.com/way-cooler/way-cooler/issues/388

**Comment by psychon** [comment]
Should be implemented by:
- 6f46b6af43c53c8074ebf3e3fe8b9a6ee49314de refresh
- 188dd1d4216f6fba0990d1aa55b7649e734a5cfb geometry
- ef0e1e484dc09b91f1287358b63c9deecc58ab50 surface

**Comment by Timidger** [comment]
Great!
