### ISSUE TITLE
AwesomeWM: mouse API

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#390]
Should be pretty basic, the only thing we are mocking is `connect_signal`, see the `Button` implementation on how to hook that up.

## Functions
- [ ] `__index`
- [ ] `__new_index`
- [x] `set_index_miss_handler`
- [x] `set_newindex_miss_handler`
- [ ] `coords`
  - [X] getting the mouse coordinates
  - [X] setting the mouse coordinates
  - [ ] Getting the button state
  - [ ] Using the boolean to control sending enter event to clients (Has to wait until the move to wlroots). Make sure to also not send the leave event if this boolean is true.
- [ ] `object_under_pointer` (requires drawin and client implementation)

**Comment by Hi-Angel** [comment]
But loading `rc.lua` doesn't yet work, does it? Putting a random text into `~/.config/way-cooler/rc.lua` makes no difference to running the binary; more over, `nm -g ./way-cooler | grep load_config` doesn't show that [`load_config()`](https://github.com/way-cooler/way-cooler/blob/be2e98136f4839b345e4cffd984dbe86dd119def/awesome/src/lua/config.rs#L20) was even built into it.

So how are you testing the API?

**Comment by Hi-Angel** [comment]
> Rust mangles its names, so that's probably why you can't find it from a `grep` (I'm guessing, I've never used `nm` with Rust, only with C).

Indeed, I just made some tests with a `test.rs`, and turns out `nm -g` doesn't see functions. However `gdb` does, as well as `rabin -s`.

Mangling usually leaves the function name part unchanged, only adds some stuff around the name.

Anyway, initially I just wanted to set a breakpoint on the function, and `gdb` definitely doesn't see `load_config`, neither does `rabin2`.

------

Sorry for asking, but could that be because it's in `awesome` subdirectory, and I also see `awesome` binary in the build? What does this do? There's no documentation on the code, so I kind of confused.

**Comment by Timidger** [comment]
There are two binaries -- one is `way-cooler` which is the compositor part of the "window manager". The `awesome`  binary works as a wayland client, similar to how the current X11 `awesome` is a client for the xserver.

`way-cooler` is designed to be small and simple, `awesome` actually implements all of the awesome stuff. Even though `awesome` depends on wlroots that is a historical accident that should be corrected since it's not a compositor but rather a wayland client.

**Comment by Hi-Angel** [comment]
> Way Cooler is in a very incomplete state right now as I'm mostly just going off the default config now since that's a very basic test case.

By "default config" I'm assuming you mean the `config/rc.lua` in build directory, right? I just tried adding some gibberish there, then running `make run`. It forced a recompile for some reason, but in the end I got again an empty black window as if config alright.

Shall I open a separate issue on this, to move the discussion there?

**Comment by AdminXVII** [comment]
You must run the separate `awesome` binary after launching way-cooler for it to read the `rc.lua` and initialize way-cooler in the proper state.

Ex:
```
cargo run --bin way-cooler &
cargo run --bin awesome
```

**Comment by Timidger** [comment]
You can do as @AdminXVII said, or use `make run` which does the same thing roughly.

The window will always appear, that is not an issue. Because the `way-cooler` binary doesn't care if `awesome` crashes or not

**Comment by Hi-Angel** [comment]
So, accidentally I stumbled upon `index()` function being unimplemented crashing awesome, now I'm trying to implement it. Could anybody explain, what that "index" supposed to do? E.g. [this documentation](https://awesomewm.org/doc/api/classes/button.html#button:set_newindex_miss_handler) mentions the `__index`, but not what it does.

I asked on IRC too, to no avail.

**Comment by Timidger** [comment]
Can you move your questions to another issue? (or continue asking them in the irc. I'll eventually see them) This is just adding noise to this one.

**Comment by Hi-Angel** [comment]
@Timidger last question is directly related to this issue.

Regarding prev. questions, I asked whether it's worth to move them into a separate issue. But not sure it's relevant anymore, given I got the answer in the next comment.

**Comment by AdminXVII** [comment]
You can generally look directly in the Awesome codebase to look what the functions does. For example, the [__index](https://github.com/awesomeWM/awesome/blob/8ac83cac5fe4fd9d7e8257df385517a479ba9d9b/mouse.c#L320) function maps to [this](https://github.com/awesomeWM/awesome/blob/8ac83cac5fe4fd9d7e8257df385517a479ba9d9b/mouse.c#L145-L181). Basically, it only supports the `screen` property, which returns the screen under the pointer.
