### ISSUE TITLE
AwesomeWM: root API

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#392]
## Functions
* [ ] `buttons`
* [ ] `keys`
* [ ] `cursor`
* [ ] `fake_input`
* [ ] `drawins`
* [ ] `wallpaper`
* [ ] `size`
* [ ] `size_mm`
* [ ] `tags`

**Comment by SethBarberee** [comment]
A few questions regarding some of these:
* What are your plans for the `wallpaper` function? Is it going to call `way-cooler-bg`?
* Keys (most likely going to be a table of similar to awesome?)

**Comment by Timidger** [comment]
> What are your plans for the wallpaper function? Is it going to call way-cooler-bg?

`way-cooler-bg` will probably be deprecated, since there's no need to have an external program for this if you can do it in Lua. Instead Way Cooler itself will handle the wallpaper and any transformations needed for the background image can be done by Lua / Cairo.

> Keys (most likely going to be a table of similar to awesome?)

Yes, if it is exposed via the Awesome API it should have the same layout as what Awesome returns (otherwise there would be too much breakage...).

The key should be pretty simple, as I assume it returns info directly from XKB. In the future we can attempt to do fancy things e.g with libinput.

**Comment by SethBarberee** [comment]
Assuming you are directly porting the API, you want something similar to this for the wallpaper?
https://awesomewm.org/doc/api/libraries/gears.wallpaper.html

**Comment by Timidger** [comment]
Yep, exactly like that

**Comment by SethBarberee** [comment]
Ok, I'll look into working on the wallpaper stuff....and gonna start learning some Rust ;)

**Comment by Timidger** [comment]
Cool! If you need any help, just ping the gitter channel and I should be able to help

**Comment by psychon** [comment]
I tried to implement `root.tags()` ontop of #508. However, I failed. My failure resulted in #507. The problem is that I somehow keep a a reference to all tags with `.activated = true`. I tried to do this with a table that is saved in the registry. Since in awesome the result of `root.tags()` preserves its order, I wanted to do a sequence (i.e. integer keys refer to tags). However, I failed to remove tags from this list.

My attempt follows bellow. The problem is that `assert!(found);` in `set_activated()` fails.
```diff
diff --git a/src/awesome/root.rs b/src/awesome/root.rs
index 56c7ca4..7ab66a2 100644
--- a/src/awesome/root.rs
+++ b/src/awesome/root.rs
@@ -84,6 +84,57 @@ fn set_wallpaper<'lua>(_: &'lua Lua, _pattern: *mut cairo_pattern_t) -> rlua::Re
 
 fn tags<'lua>(lua: &'lua Lua, _: ()) -> rlua::Result<Table<'lua>> {
     let table = lua.create_table()?;
-    // TODO FIXME Get tags
+    let activated_tags = lua.named_registry_value::<Table>(super::tag::TAG_LIST)?;
+    for pair in activated_tags.clone().pairs::<Value, Value>() {
+        let (key, value) = pair?;
+        table.set(key, value)?;
+    }
     Ok(table)
 }
+
+#[cfg(test)]
+mod test {
+    use rlua::Lua;
+    use super::super::root;
+    use super::super::tag;
+
+    #[test]
+    fn tags_none() {
+        let lua = Lua::new();
+        tag::init(&lua).unwrap();
+        root::init(&lua).unwrap();
+        lua.eval(r#"
+local t = root.tags()
+assert(type(t) == "table")
+assert(type(next(t)) == "nil")
+"#, None).unwrap()
+    }
+
+    #[test]
+    fn tags_does_not_copy() {
+        let lua = Lua::new();
+        tag::init(&lua).unwrap();
+        root::init(&lua).unwrap();
+        lua.eval(r#"
+local t = tag{ activated = true }
+local t2 = root.tags()[1]
+assert(t == t2)
+t2.name = "Foo"
+assert(t.name == "Foo")
+"#, None).unwrap()
+    }
+
+    #[test]
+    fn tags_some() {
+        let lua = Lua::new();
+        tag::init(&lua).unwrap();
+        root::init(&lua).unwrap();
+        lua.eval(r#"
+local first = tag{ activated = true }
+local second = tag{ activated = true }
+local t = root.tags()
+assert(t[1] == first)
+assert(t[2] == second)
+"#, None).unwrap()
+    }
+}
diff --git a/src/awesome/tag.rs b/src/awesome/tag.rs
index 849ab20..86a4d21 100644
--- a/src/awesome/tag.rs
+++ b/src/awesome/tag.rs
@@ -2,12 +2,14 @@
 
 use std::fmt::{self, Display, Formatter};
 use std::default::Default;
-use rlua::{self, Table, Lua, UserData, ToLua, Value, UserDataMethods, AnyUserData};
+use rlua::{self, Table, Lua, UserData, ToLua, Value, UserDataMethods, AnyUserData, Integer};
 use super::object::{self, Object, Objectable};
 use super::class::{self, Class, ClassBuilder};
 use super::property::Property;
 use super::signal;
 
+pub const TAG_LIST: &'static str = "__tag_list";
+
 #[derive(Clone, Debug)]
 pub struct TagState {
     name: Option<String>,
@@ -55,6 +57,7 @@ impl UserData for TagState {
 }
 
 pub fn init(lua: &Lua) -> rlua::Result<Class> {
+    lua.set_named_registry_value(TAG_LIST, lua.create_table()?)?;
     method_setup(lua, Class::builder(lua, "tag", None)?)?
         .save_class("tag")?
         .build()
@@ -132,7 +135,28 @@ fn set_activated<'lua>(lua: &'lua Lua, (obj, val): (AnyUserData<'lua>, bool))
         }
         tag.activated = val;
     }
-    if !val {
+    let activated_tags = lua.named_registry_value::<Table>(TAG_LIST)?;
+    let activated_tags_count = activated_tags.len()?;
+    if val {
+        let index = activated_tags_count + 1;
+        println!("Setting tag {:?} at index {}", &tag.get_object()? as *const _, index);
+        activated_tags.set(index, obj.clone())?;
+    } else {
+        let tag_ref = &tag.get_object()? as *const _;
+        let mut found = false;
+        for pair in activated_tags.clone().pairs::<Integer, AnyUserData>() {
+            let (key, value) = pair?;
+            if tag_ref == &Tag::cast(value.into())?.get_object()? as *const _ {
+                found = true;
+                /* Now remove this... */
+                for index in key .. activated_tags_count-1 {
+                    activated_tags.set(index,
+                                       activated_tags.get::<_, Value>(index + 1)?)?;
+                }
+                break;
+            }
+        }
+        assert!(found);
         set_selected(lua, (obj.clone(), false))?;
     }
     signal::emit_object_signal(lua,
```
My next best idea would be to create a counter `AtomicUsize` in a `lazy_static!` and use `.fetch_add(1, Ordering::Relax)` to give each tag a unique identifier that can be used for comparisons. However: Ewwwww.

Another idea would be to just ignore the order of tags and use the keys of the table to reference them (i.e. `__tag_list[tag] = true`). However, for this I would first like to have an okay that I may ditch the order here. (In theory it should not be needed, `awful.tag` implements its own scheme for establishing an order of tags)
