### ISSUE TITLE
Way Cooler can't find libwayland-server.so.0

### ISSUE THREAD

**Issue by mark-blum** [way-cooler/way-cooler#395]
On Ubuntu 17.04, for whatever reason, `libwayland-server.so.0` and `libwayland-server.so.0.1.0` exist, but `libwayland-server.so` does not exist, and `libloading` (the library that ultimately searches for the library) can not find `libwayland-server.so.0` from the given library name `libwayland-server.so`.

I was able to fix this issue on my end by making `libwayland-server.so` symlinked to `libwayland-server.so.0` however it might be better to look for `libwayland-server.so.0` instead.

**Comment by mark-blum** [comment]
I should mention the issue lives within `wayland_sys`, and a similar issue happens for sample client applications when looking for `libwayland-client.so`

**Comment by Timidger** [comment]
I suggest reporting this bug to https://github.com/vberger/wayland-rs, as it's probably a bug in how they find what library to link to with their build script (if you provide a log of the compilation failing in verbose mode (`--verbose`) then I might be able to learn when the linker is trying to find the library).

**Comment by mark-blum** [comment]
This is not a compilation error, but a runtime issue. You see `wayland-sys` has a feature ("dlopen", which you seem to have enabled) where it will programmatically look for and load `libwayland-server.so`. The error you get is a way-cooler panicking when you run it on not finding `libwayland-server.so` and giving a nice backtrace.

Relevant line from wayland-sys loading the library here: https://github.com/Smithay/wayland-rs/blob/8bf61dd6d5fefc43837ae17ca3c74e64e23db40f/wayland-sys/src/server.rs#L138

However I have reported the issue [to wayland-rs](https://github.com/Smithay/wayland-rs/issues/139) and am working on a pull request to handle this case as well

**Comment by LennyPenny** [comment]
I'm still getting this issue on ubuntu 17.10
```
thread 'main' panicked at 'Library libwayland-server.so could not be loaded.', /checkout/src/libcore/option.rs:823
```

Is this the same bug or a something else?

**Comment by mark-blum** [comment]
Yes, since this crate hasn't updated its `wayland-sys` to the version with the fix. Until that dependency gets update, try my solution at the top and see if it starts working. (You'll probably have to do the same for `libwayland-client.so` to get the built in apps working). They should be somewhere like `/usr/lib/aarch64-linux-gnu/libwayland-client.so.0`

**Comment by Timidger** [comment]
@mark-blum oh I never updated the cargo lock? I should probably fix that then

**Comment by LennyPenny** [comment]
Are there any breaking changes in the newer wayland-sys versions? 
I'm guessing no if it follows semantic vesioning 

I could just make a quick PR to bump it to the latest version

**Comment by Timidger** [comment]
As long as it wasn't the minor version (since it's technically < 1.0, wayland-sys can have breaking changes on minor version bumps but not patch bumps (e.g the last number).

If so, open a PR and I'll merge it. We don't use much of it, so the amount of breakage that can happen is minor (and easy to spot)

**Comment by LennyPenny** [comment]
wayland-sys 9.10 might just be enough at it was released 6 days after @mark-blum's PR was merged into wayland-rs
I will try once I resolve my issues building/running this #426

**Comment by Timidger** [comment]
Putting this in 0.7 since it's an easy fix (updating the version number of wayland-sys)
