### ISSUE TITLE
Segfault when running without systemd (voidlinux)

### ISSUE THREAD

**Issue by Guppster** [way-cooler/way-cooler#399]
I'm trying to install way-cooler on voidlinux and run from tty. I run into a segmentation fault 

```
$ way-cooler --version
Way Cooler 0.6.2
Way Cooler IPC version 1
```

```
$ ldd --version
ldd (GNU libc) 2.26
```

```
$ ls -la /usr/bin/way-cooler
-rwsr-xr-x 1 root root 28614904 Sep 13 14:20 /usr/bin/way-cooler
```

```
$ getcap /usr/bin/way-cooler

```
I have tried every combination of setcap (https://github.com/SirCmpwn/sway/issues/1022) and setuid with no success. 

Full Log: https://gist.github.com/Guppster/595b92d8d49c0d390c42dfa630889fb5
strace: https://gist.github.com/Guppster/9cf1fbc5f0a434eace5aea6403e123d4

I ran into a similar problem with sway [here](https://github.com/SirCmpwn/sway/issues/1356) and couldn't come to a solution. 

Some previous discussion can be found in #351

**Comment by Timidger** [comment]
From the logs it looks like you have two monitors connected, and one of them has no mode setting available to it. Perhaps WLC is trying it initialize it when it can't. Can you disconnect the monitor that isn't plugged into HDMI-A-1?

**Comment by Guppster** [comment]
Just for the record in case this means anything to anyone: Originally i had installed wlc using void's package manager xbps, but during the `cargo install way-cooler` process i received an error saying that `ld -l wlc` returned `not found`. I then installed `wlc-devel` and that let me continue the cargo install process but `ld -l wlc` now returns `ld: warning: cannot find entry symbol _start; not setting start address`. Not sure if that indicates anything important. 

I'll report back after removing a monitor

**Comment by Guppster** [comment]
Looks like the same thing is happening when i run with a single monitor: https://gist.github.com/Guppster/d0c5b583922658d99c38a6fdca5f240d

I just tried installing way-cooler on my laptop running a very similar setup (void i686 glibc) and ended up with another segfault: https://gist.github.com/Guppster/886673be78f1d790fba37959b84edf3f

**Comment by Guppster** [comment]
```
$ dbus-test-tool black-hole
Failed to connect to bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```

```
$ lspci -k |grep VGA -A 2
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]
        Subsystem: XFX Pine Group Inc. Double D HD 7970
        Kernel driver in use: radeon
```

**Comment by alexander-smoktal** [comment]
Hey, @Guppster , could you rebuild wlc from master and try again. I had the same issue. But the've merged a fix, which may solve this.

**Comment by Guppster** [comment]
Awesome!! Thanks for following up on the issue. Just tested it out and it works!! Can't wait to finally start using way-cooler.

For other people with this problem, heres what i had to do to solve my issue:
Get the latest wayland: https://wayland.freedesktop.org/releases/
Build following this: http://www.linuxfromscratch.org/blfs/view/svn/general/wayland.html
Note: I needed to do this because when i built wlc/master in the next step I was missing the wayland-scanner executable. The wayland i got from xbps didn't have the scanner.. i guess

Clone and Build: https://github.com/Cloudef/wlc
Copy libwlc.so & libwlc.so.0 from .../wlc/target/src/ to /usr/lib

Clone way-cooler and run cargo build.

Again, thanks for following up on this @alexander-smoktal i almost lost hope lol
