### ISSUE TITLE
Display errors (e.g. no status bar)

### ISSUE THREAD

**Issue by Rikorose** [way-cooler/way-cooler#403]
Hi,

i compiled way-cooler from source and installed it via:
```sh
cd projects/way-cooler/
git checkout v0.6.2
cargo build --release
cp target/release/way-cooler /usr/bin
cp config/init.lua ~/.config/way-cooler

dbus-launch --exit-with-session way-cooler 
```

Way Cooler starts up and displays the mouse, but nothing else. Killing via Alt+Shift+Esc works but nothing else.

Here is my debug log:
https://gist.github.com/Rikorose/8f28b5f2bd2ec3ecb03aaf8c976ead7c

**Comment by Timidger** [comment]
Based on your title, are you expecting a status bar? Way Cooler doesn't have a status bar yet. If you are basing your assumptions off of the pictures I have posted of Way Cooler that is using [lemonbar](https://github.com/LemonBoy/bar). There is no official, bundled status bar yet.
