### ISSUE TITLE
A Tabbed/Stacked nested in another Tabbed/Stacked container doesn't properly show the focused view

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#407]
To reproduce issue:

1) Spawn Tabbed/Stacked container
2) Make a Tabbed/Stacked container inside of that first Tabbed/Stacked container
3) Add a new view to that nested container
4) Notice that you can only see the latest one, not any the previous ones that you spawned.

**Comment by alexander-smoktal** [comment]
I'll try to fix this one

**Comment by alexander-smoktal** [comment]
Fixed

**Comment by Timidger** [comment]
Correct, not sure why it didn't close automatically haha

**Comment by Timidger** [comment]
Note that this issue was not totally fixed by @alexander-smoktal patch, as it caused a regression. Going to keep this closed since it is fixed but refer to #413 for further discussion
