### ISSUE TITLE
Title bar doesn't work properly in case its size differs from the size of borders

### ISSUE THREAD

**Issue by alexander-smoktal** [way-cooler/way-cooler#410]
Steps to reproduce:
1. Open `~/.config/way-cooler/init.lua`
2. Change `way_cooler.windows.borders.size` to `10`
3. Run binary

Result: container title bar is too narrow. There is a hole below.

**Comment by Timidger** [comment]
Thanks for the report, there's probably a hardcoded number somewhere that's incorrect.

For anyone wanting to work on it, the problem is probably somewhere in [here](https://github.com/way-cooler/way-cooler/tree/master/src/layout/core/borders)

**Comment by Timidger** [comment]
If I had to guess, it's probably [this little number](https://github.com/way-cooler/way-cooler/blob/master/src/layout/core/borders/container_draw.rs#L32)

**Comment by Arnaz87** [comment]
I think the issue may be in [this line](https://github.com/way-cooler/way-cooler/blob/5d4b00fa1efd8e1bb56602fda85bebd32794739a/src/layout/core/borders/container_draw.rs#L67), the height of the drawing geometry is being set to thickness, which is always the edge thickness times 2, not considering at all the title bar height.
