### ISSUE TITLE
Topmost floating window is not always the active one

### ISSUE THREAD

**Issue by alexander-smoktal** [way-cooler/way-cooler#415]
Topmost floating window is always the same. But it'd be better to have active floating window on top. 
To reproduce:
1. Create 2 floating windows;
2. Switch to the first one;

Result: Active floating window is hidden by the last one.

**Comment by alexander-smoktal** [comment]
@Timidger , how do you think, what is the best way to fix the issue? 
I've tried to draw active floating on-top, but when I switch to grounded window, the last floating raise up.
Also I've tried to reparent active floating to the same parent. In this case active floating becomes the last one and I just can't switch to grounded windows.
If reparent all other floating windows, it'd be impossible to switch between more then 3 floating windows.
I'm thinking about storing last floating window and check if user switches to floating window, then switch to last active floating window. But in this case window order is unpredictable.

**Comment by Timidger** [comment]
Off the top of my head, the easiest way to fix this is to add this to `focus_on`:

```rust
match self.tree[node_ix] {
    Container::View { floating, handle, .. } => {
        if floating {
            handle.bring_to_front();
        }
    },
    ...
}
```

**Comment by Timidger** [comment]
@alexander-smoktal 

Oh wait sorry now looking at this issue more deeply I see that won't fix the underlying issue.

As a proper answer to your question: we have a active count for all nodes that you can use to find the most recently used window. Get a list of the active nodes, filter by floating, and use that to raise them in the proper order. That's a complicated fix though, so let me see if there's a better way to fix this...
