### ISSUE TITLE
Wrong keybindings / keyboard layout

### ISSUE THREAD

**Issue by Helvethor** [way-cooler/way-cooler#416]
Hi there,

I'm trying to configure way-cooler but stumbled some layout related problems.
When I start way-cooler, the keyboard types in qwerty. localectl status returns the following:

```
$ localectl status
   System Locale: LANG=en_US.UTF-8
       VC Keymap: fr_CH
      X11 Layout: ch
     X11 Variant: fr
```

Nonetheless, after I run setxkbmap ch the keyboard types ok. But way-cooler's keybindings still use a qwerty layout... This means keybindings like mod + y or mod + z don't work.

Is this normal? Does it work for other people?

Regards,
Vincent

**Comment by Timidger** [comment]
`setxkbmap` is an X utility, it doesn't work in Wayland.

Please set your `XKB_DEFAULT_LAYOUT` before starting Way Cooler
