### ISSUE TITLE
Can't build with rustc 1.14.0 due to undefined macro eprintln! in rlua

### ISSUE THREAD

**Issue by l0b0** [way-cooler/way-cooler#418]
Building https://aur.archlinux.org/packages/way-cooler-git/ on an up-to-date Arch Linux using `makepkg --syncdeps --install` fails:

> error: macro undefined: 'eprintln!'
>    --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.9.4/src/util.rs:306:21
>     |
> 306 |                     eprintln!("Lua memory error, aborting!");
>     |                     ^^^^^^^^
>     |
>     = help: did you mean `println!`?
> 
> error: macro undefined: 'eprintln!'
>    --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.9.4/src/util.rs:313:21
>     |
> 313 |                     eprintln!("Lua error during __gc, aborting!");
>     |                     ^^^^^^^^
>     |
>     = help: did you mean `println!`?
> 
> error: macro undefined: 'eprintln!'
>    --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.9.4/src/util.rs:527:17
>     |
> 527 |                 eprintln!("Lua error during __gc, aborting!");
>     |                 ^^^^^^^^
>     |
>     = help: did you mean `println!`?
> 
> error: macro undefined: 'eprintln!'
>    --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.9.4/src/lua.rs:471:21
>     |
> 471 |                     eprintln!("Out of memory in Lua allocation, aborting!");
>     |                     ^^^^^^^^
>     |
>     = help: did you mean `println!`?
> 
> error: aborting due to 4 previous errors
> 
> Build failed, waiting for other jobs to finish...
> error: Could not compile `rlua`.
> 
> To learn more, run the command again with --verbose.
> ==> ERROR: A failure occurred in build().
>     Aborting...

**Comment by Timidger** [comment]
We only officially support the latest stable release of Rust. Please update your compiler.
