### ISSUE TITLE
Support assigning seats to windows

### ISSUE THREAD

**Issue by moonheart08** [way-cooler/way-cooler#419]
wl_seats are groups of inputs. We should be able to create these and assign them to windows (So windows take input from that seat)
It could be useful for, say, playing 4 instances of a game with friends (Allows assigning a controller to each instance)

**Comment by Timidger** [comment]
This isn't possible with wlc, it will be possible once we switch to [wlroots](https://github.com/swaywm/wlroots). Check back then
