### ISSUE TITLE
Mouse movement downwards and to the right doesn't work properly

### ISSUE THREAD

**Issue by TheLostLambda** [way-cooler/way-cooler#420]
Hello all, I was really excited to use way-cooler, but I am currently having unbearable mouse issues. I seems to be exactly the issue talked about here: https://github.com/Cloudef/wlc/issues/181https://github.com/Cloudef/wlc/issues/181

I am not certain where this mouse processing happens in way-cooler, but I would love to have this fixed so that I can actually use the wm.

**Comment by Timidger** [comment]
That bug was fixed as you see, but we haven't implemented the change in rust WLC or way cooler.

Feel free to submit a patch fixing that, but I won't because we are moving to wlroots in the future. If you want to work on it I'll be happy to provide guidance (best reached on the gitter channel).

**Comment by TheLostLambda** [comment]
Okay, what is entailed in switching to wlroots? I would be interested in helping with that where possible.

**Comment by Timidger** [comment]
See the repo [here](https://github.com/swaywm/wlroots-rs), I have some issues up which I'm expand over the next couple of days. Feel free to also discuss changes on our gitter feed or in the sway-devel irc
