### ISSUE TITLE
AUR Package doesn't seem to work

### ISSUE THREAD

**Issue by omtcvxyz** [way-cooler/way-cooler#422]
I have just built way-cooler and installed the [AUR package](https://aur.archlinux.org/packages/way-cooler/) and I get thrown back to SDDM shortly logging into Way-Cooler.

Tried with both

```
$ rustc --version
rustc 1.21.0 (3b72af97e 2017-10-09)
```

And

```
rustc --version
rustc 1.20.0 (f3d6973f4 2017-08-27)
```

Here's what I get when running `$ way-cooler` from within KDE Plasma 5.11.2: [log for 1.21.0](https://gist.github.com/omtcyfz/fc575044e90dadf22a05cbdc0e83e78d) and [log for 1.20.0](https://gist.github.com/omtcyfz/72cd7f5f7526ce0271116901410557f0).

Getting `Segmentation fault (core dumped)` in both cases.

**Comment by Timidger** [comment]
Dup with https://github.com/way-cooler/way-cooler/issues/421?

I'm not at my computer right now, but I can debug this in a couple of hours.

Off the top of my head: has there been a backwards incompatible change in wlc recently? They could cause the segfault potentially

**Comment by omtcyfz** [comment]
@Timidger I've seen that one, but I am not sure whether they are equivalent. Since that report is for the `-git` version of the package. Since I am not familiar with the project internals I thought a separate issue might be reasonable.

**Comment by Timidger** [comment]
Ah ok then I'll keep both up then

**Comment by omtcyfz** [comment]
@Timidger thanks!

Also, the failure logs seem to contain similar parts and yet somewhat different, though again I am not able to understand how close those two are.

**Comment by Timidger** [comment]
Hmm, I can't reproduce this issue at all...

Can you reproduce this on sway at all? E.g does sway also segfault?

**Comment by Timidger** [comment]
Have you tried installing [from the site](http://way-cooler.org/download/)? That statically compiles wlc so if there's any linking/ABI issues (which Is what I suspect) then this should work (if not, it's something else causing the problem)

**Comment by omtcyfz** [comment]
> Can you reproduce this on sway at all? E.g does sway also segfault?

No, Sway does not. I tried installing and launching Sway yesterday, worked fine.

**Comment by Timidger** [comment]
Can you please give me a core dump with debug symbols enabled then please? It would help me debug the issue
