### ISSUE TITLE
Would you ever support redox os?

### ISSUE THREAD

**Issue by that1communist** [way-cooler/way-cooler#428]
Their current window-manager is terrible, and this is written in rust.

I don't know how difficult it'd be, but they need the help.

https://www.redox-os.org/

**Comment by Timidger** [comment]
AFAIK Redox uses its own display manager stack. At a bare minimum, redox would need to support the same DRM api that Wayland/Way Cooler uses to draw to the screen (not to mention cario and all the other dependencies).

It is unlikely that will happen. Let me know if they get Wayland support though.

**Comment by Timidger** [comment]
To add on to this: I haven't spoken with the redox devs at all, but from what I've seen of the development as an outsider they want to build their own system not based on traditional Unix-likes (including the gui, which is why they aren't implementing Wayland). Things could have changed, or I could just be misunderstanding their goals.

**Comment by that1communist** [comment]
https://doc.redox-os.org/book/introduction/what_is_redox.html

it says its supposed to be able to run linux applications just fine, later on, so i'd assume they'd have to support wayland/x.org to some extent, right? I don't actually know though.

I would assume that a window manager counts as an application? but i'm not actually sure, and i'm sure you know far better than I do the answer to that question.

**Comment by Timidger** [comment]
Most of the reason I don't think it will happen is [this thread](https://github.com/redox-os/redox/issues/130).

Supporting Wayland requires significant kernel work (eg I don't know if they implement DRM, I have a feeling they don't), and if the work can't be justified for other Linux applications I did see it being a thing.

I'll wait and see what happens

**Comment by Timidger** [comment]
And a window manager is technically an application, but an application that talks more or less directly to certain kernel interfaces. And that link you sent specifically says they are not POSIX compliant

**Comment by mitchtbaum** [comment]
From this thread, [Is redox going to support wayland?](https://www.reddit.com/r/Redox/comments/7dedsz/is_redox_going_to_support_wayland/), it looks like with a port of Mesa and a graphics driver it would be possible.
