### ISSUE TITLE
Segfault when spawning programs

### ISSUE THREAD

**Issue by Arnaz87** [way-cooler/way-cooler#430]
On Manjaro, building from source on `rustc 1.23.0-nightly (d6b06c63a 2017-11-09)`

The WM opens without problems in both X and in a TTY, but segfaults when I try to open a program in both.

This is the log, run from the TTY, when I open a terminal inside way-cooler

[wc.log](https://github.com/way-cooler/way-cooler/files/1462072/wc.log)

The last trace line is because i added these lines in *src/layout/commands.rs:465*

~~~ rust
trace!("Calling view.get_type() with {:?}", view);
let view_bit = view.get_type();
trace!("After view.get_type()");
~~~

So I know the function that's failing is `WlcView.get_type`.

It also fails the same way when I open *dmenu*, and also when I open a gnome app in X (because of the gnome bug that opens a window in a wayland server if there's one)

**Comment by Timidger** [comment]
Hmmmm

What version of wlc are you running? Can you reproduce this using stable rustc? I only try to target the latest  stable Rust.

**Comment by Arnaz87** [comment]
The crate is **rustwlc 0.6.3**, and according to pacman i'm using **wlc 0.0.10-1** in my system.

I compiled it again with `rustc 1.21.0 (3b72af97e 2017-10-09)`, but the same happens.
[Here is the log](https://github.com/way-cooler/way-cooler/files/1462684/wc.log)

Sway does work perfectly though.

**Comment by Timidger** [comment]
Can you provide a core dump with debug symbols?

**Comment by Arnaz87** [comment]
How do I do that?

**Comment by Timidger** [comment]
@Arnaz87 can you point your rustwlc dependency in your `Cargo.toml` to [this git branch](https://github.com/way-cooler/rust-wlc/tree/bugfix/incorrect_get_type_return_type)? This _might_ solve the problem.

**Comment by Arnaz87** [comment]
Well, sorta, now it's a different crash.
[Log](https://github.com/way-cooler/way-cooler/files/1462852/wc.log)
[Core dump](https://github.com/way-cooler/way-cooler/files/1462867/wc.dump.gz)
I just learn how to core dump, if it has something wrong please let me know.

**Comment by Timidger** [comment]
Hm, can't get it to read the symbols correctly on that coredump for some reason.

Can you get a backtrace e.g from `gdb` on the corefile / from running `way-cooler`? That might indicate where the issue is (e.g another rust-wlc issue or a bug in wlc)

**Comment by Timidger** [comment]
Ok pushed another change to that branch. Recompile with the newest changes and lets see how we go.

Do you have an odd architecture or something? These issues I'm finding are obviously UB, but it's strange I haven't heard about it until now. Or are you updating the bitfields dependency for rust wlc manually?

**Comment by Arnaz87** [comment]
Yes, it works now. I wasn't doing anything fancy yet, i'm still trying to get it running. I'm on a 32bit x86 system, not really that odd, maybe way-cooler has only been used on 64bit systems until now, as that's currently the norm.

**Comment by Timidger** [comment]
Yes that's probably it...I haven't got any 32 bit computers to test it on unfortunately. Glad to hear we fixed the issue!

I'll push a release for rust-wlc, update way-cooler, and get this fix out in the next release. Thanks for the bug report and being patient while I tracked the issue down.
