### ISSUE TITLE
Display tabbed and stacked containers' title bars like i3

### ISSUE THREAD

**Issue by Arnaz87** [way-cooler/way-cooler#436]
Display tabs' title bars side to side on the container title bar, instead of how they are being displayed right now, counting the contained tabs. Similarly, stacked container should display the titles of it's children on top of one another.

**Comment by Timidger** [comment]
Your welcome to send a patch, but I am not planning to do this in the near future.

**Comment by Timidger** [comment]
This has mostly been fixed, there are a few remaining issues. Namely #440, #442, and #443.

Going to go ahead and close this though.
