### ISSUE TITLE
trackpad option support?

### ISSUE THREAD

**Issue by that1communist** [way-cooler/way-cooler#438]
on sway 

```
input "0:0:Atmel_maXTouch_Touchpad" {
    tap enabled
    natural_scroll disabled
}
```

This will let me tap to click, I can't find an equivalent on way-cooler, is there one and I missed it? I searched the issues.

**Comment by Timidger** [comment]
What you're looking for is [this issue for libinput configuration](https://github.com/way-cooler/way-cooler/issues/189).

It's not currently implemented, and though there's been interest in it I haven't had time to work on it. I plan to work on it post-move-to-wlroots. Realistically, it won't be a feature for at least several months.

If you want to work on adding this feature I can provide feedback and help. It shouldn't be very difficult, though it might require making changes in rust-wlc as well as Way Cooler.

**Comment by that1communist** [comment]
if it relies on changes in wlc, then i'd think you'd want to wait until wlroots came out, so as to not waste effort, so yeah.

**Comment by Timidger** [comment]
It wouldn't be hard to port over, most of the work is likely just configuration work (eg adding it so you can make the modifications in Lua). I haven't looked at the wlc interface in a while / how sway implemented it, but I think they both send info directly to libinput to it should be roughly the same
