### ISSUE TITLE
WM Won't Load

### ISSUE THREAD

**Issue by FireAntJoe** [way-cooler/way-cooler#441]
When I try to load the WM from GDM I go to a black screen.Then it goes back to GDM.

**Comment by Timidger** [comment]
For posterity, discussion thus far from email:


```

**Comment by FireAntJoe** [comment]
Thank you. Will attach the log file to this thread.
[log.txt](https://github.com/way-cooler/way-cooler/files/1504423/log.txt)

**Comment by Timidger** [comment]
Looks like it starts up and closes ok. Are you running this in a TTY? Try running from X or another wayland compositor to see if it does this still.

Also, run it like this and post the log file from that:

`WLC_DEBUG="commit,xwm,request" way-cooler`

**Comment by FireAntJoe** [comment]
I am trying this is in i3 and alatricity(I spelled that wrong).

**Comment by Timidger** [comment]
Try running it in a tty then to see if there's a change. (e.g switch to tty2, log in, and then run `way-cooler &> log.txt`). It's possible i3 is interacting badly with it (though it would surprise me)

**Comment by FireAntJoe** [comment]
I switched to tty and here are the results.
[log3.txt](https://github.com/way-cooler/way-cooler/files/1504459/log3.txt)

**Comment by Timidger** [comment]
From the log it looks like you are trying to spawn a terminal using the default command, but you don't have `weston-terminal` installed. Either change the string in the configuration to a terminal you have on your machine (e.g `gnome-terminal`) or install `weston-terminal` (usually provided by the `weston` package)

**Comment by Timidger** [comment]
You also don't have the background program, which can be found [here](https://github.com/way-cooler/way-cooler-bg)

**Comment by Timidger** [comment]
Was your issue fixed?

**Comment by FireAntJoe** [comment]
Yes.

**Comment by FireAntJoe** [comment]
I tried that stuff and still not working. I will look at this window manager in the future when it is more stable.
