### ISSUE TITLE
Documentation improvement: installation

### ISSUE THREAD

**Issue by asmjmisc** [way-cooler/way-cooler#465]
Hi, I just now found out about `way-cooler` and wanted to try it out. I come from using `XMonad` and `i3wm`, so I was enticed into trying way-cooler.

Like any user would do, I headed to [the projects homepage](http://way-cooler.org/) and went straight for the documentation. However, after skimming over the site, I didn't find an explicit section on installation. There are sections concerning the usage and operation (the D-Bus and Lua ones) of the window manager, but not installation.

Considering Rust and its tooling ecosystem are relatively new, I find that this could be a point of confusion or a stumbling block to anyone unfamiliar yet willing to try running tools that live in that ecosystem. I think it would be beneficial to describe correct or preferred manners of installing software written in Rust (in the context of `way-cooler`) that would alleviate new user entry. I believe this would also provide for better issue reporting and error troubleshooting if the installation path is somewhat predefined or at least commonly understood.

**Comment by Timidger** [comment]
There is installation instructions [in the README](https://github.com/way-cooler/way-cooler#installation) and we also have a [download page on the website](http://way-cooler.org/download).

The website is currently a little slapped together, I'll probably clean it up in the future to make it more user friendly (e.g better download links). For now though I think there are sufficient links and instructions on how to download Way Cooler, they just may be slightly hidden.
