### ISSUE TITLE
XDG_RUNTIME_DIR not set!

### ISSUE THREAD

**Issue by vitorhugomattos** [way-cooler/way-cooler#473]
I got this error after installing way cooler. i did some research, and discovered this variable is set by systemd, but my distribution uses another init system: runit. is this the cause for the error? there is a real need for this variable in the execution of the wm?

* Way Cooler version: 0.7.0 (IPC version 1)
* Debug log:
`INFO [way_cooler] src/main.rs:214 Logger initialized, setting wlc handlers.
INFO [way_cooler] src/main.rs:219 LS_COLORS: no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.svgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.bz2=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.svg=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:
INFO [way_cooler] src/main.rs:219 LANG: pt_BR.UTF-8
INFO [way_cooler] src/main.rs:219 SUDO_GID: 1000
INFO [way_cooler] src/main.rs:219 USERNAME: root
INFO [way_cooler] src/main.rs:219 SUDO_COMMAND: /bin/bash
INFO [way_cooler] src/main.rs:219 USER: root
INFO [way_cooler] src/main.rs:219 LC_COLLATE: C
INFO [way_cooler] src/main.rs:219 PWD: /home/vitor
INFO [way_cooler] src/main.rs:219 HOME: /root
INFO [way_cooler] src/main.rs:219 SUDO_USER: vitor
INFO [way_cooler] src/main.rs:219 SUDO_UID: 1000
INFO [way_cooler] src/main.rs:219 MAIL: /var/mail/root
INFO [way_cooler] src/main.rs:219 SHELL: /bin/bash
INFO [way_cooler] src/main.rs:219 TERM: linux
INFO [way_cooler] src/main.rs:219 SHLVL: 1
INFO [way_cooler] src/main.rs:219 LOGNAME: root
INFO [way_cooler] src/main.rs:219 PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
INFO [way_cooler] src/main.rs:219 _: /usr/bin/way-cooler
INFO [way_cooler] src/main.rs:219 OLDPWD: /home/vitor/wayland
ERROR [way_cooler] src/main.rs:105 XDG_RUNTIME_DIR is not set!`

running in void linux with way-cooler installed via xbps package manager.

**Comment by Timidger** [comment]
This is required by Wayland. Please set the environment variable and try to run Way Cooler again.

I don't know why Void wouldn't have set it, since this is a pretty common environment variable.

**Comment by vitorhugomattos** [comment]
yeah. systemd sets it, but runit don't. i'll try to configure ruinit or bash to do so. thnx.

![screenshot_23](https://user-images.githubusercontent.com/2721565/35367395-3a26a892-0165-11e8-87a5-eaa65bfb4bf3.png)
