### ISSUE TITLE
No borders are displayed for top-level containers at first workspace just after startup

### ISSUE THREAD

**Issue by edubenetskiy** [way-cooler/way-cooler#496]
If I create a root-level tabbed layout, no border is displayed for any of the tabbed windows nor for the container itself, so I don't know if there are multiple windows or not and even how they are named:

![screenshot](https://user-images.githubusercontent.com/8538359/36364747-0acee748-1557-11e8-84f4-86fcd598f115.png)

This issue is similar to #315.

I am using Polybar, but it is configured (see below) as the `x11_bar` and does not overlap the containers. Non-root level tabbed/stacked layouts do work as expected, and so do the top-level horizontal/vertical layouts:

![screenshot](https://user-images.githubusercontent.com/8538359/36364991-6cf777e0-1558-11e8-8a1d-62e08778b1e6.png)

## Context

Arch Linux + Wayland.

Way Cooler installed with the official installation script from http://way-cooler.org:

```bash
curl https://way-cooler.github.io/way-cooler-release-i3-default.sh -sSLf | bash -s  way-cooler-bg  wc-grab  wc-lock
```

### Way Cooler version

```
$ way-cooler --version
Way Cooler 0.8.0
Way Cooler IPC version 1
```
### init.lua

```lua
way_cooler.programs = {
  x11_bar = "polybar-wayland_XWAYLAND0"
}

way_cooler.bar = "polybar"

util.program.spawn_at_startup("polybar", "wayland")
util.program.spawn_at_startup("wc-bg", "-f solar_system.jpg", "-m tile")

local active = "40798c"
local inactive = "353a47"

way_cooler.windows = {
  gaps = { -- Options for gaps
    size = 0, -- The width of gaps between windows in pixels
  },
  borders = { -- Options for borders
    root_borders = false, -- Display borders in root containers by default
    size = 15, -- The width of the borders between windows in pixels
    inactive_color = inactive, -- Color of the borders for inactive containers
    active_color = active -- Color of active container borders
  },
  title_bar = { -- Options for title bar above windows
    size = 20, -- Size of the title bar
    background_color = inactive, -- Color of inactive title bar
    active_background_color = active, -- Color of active title bar
    font_color = "808080", -- Color of the font for an inactive title bar
    active_font_color = "ffffff" -- Color of font for active title bar
  }
}

way_cooler.mouse = {
  lock_to_corner_on_resize = false
}

mod = "Super"

local key = way_cooler.key

local keys = {
  -- Open dmenu
  key({ mod }, "e", util.program.spawn_once("rofi", "-show run")),

  -- Open terminal
  key({ mod }, "return", util.program.spawn_once("lxterminal")),

  -- Lock screen
  key({ mod, "Shift" }, "l", util.program.spawn_once("wc-lock")),

  -- Lua methods can be bound as well
  key({ mod, "Shift" }, "h", function () print("Hello world!") end),

  -- Some Lua dmenu stuff
  key({ mod }, "l", "dmenu_eval"),

  -- Move focus
  key({ mod }, "left", "focus_left"),
  key({ mod }, "right", "focus_right"),
  key({ mod }, "up", "focus_up"),
  key({ mod }, "down", "focus_down"),
  --
  key({ mod }, "h", "focus_left"),
  key({ mod }, "s", "focus_right"),
  key({ mod }, "n", "focus_up"),
  key({ mod }, "t", "focus_down"),

  -- Move active container
  key({ mod, "Shift" }, "left", "move_active_left"),
  key({ mod, "Shift" }, "right", "move_active_right"),
  key({ mod, "Shift" }, "up", "move_active_up"),
  key({ mod, "Shift" }, "down", "move_active_down"),
  --
  key({ mod, "Shift" }, "h", "move_active_left"),
  key({ mod, "Shift" }, "s", "move_active_right"),
  key({ mod, "Shift" }, "n", "move_active_up"),
  key({ mod, "Shift" }, "t", "move_active_down"),

  -- Split containers
  key({ mod }, "m", "split_horizontal"),
  key({ mod }, "v", "split_vertical"),
  key({ mod }, "z", "horizontal_vertical_switch"),
  key({ mod }, "c", "tile_stacked"),
  key({ mod }, "w", "tile_tabbed"),
  key({ mod }, "f", "fullscreen_toggle"),
  -- key({ mod, "Shift" }, "q", "close_window"),
  key({ mod }, "x", "close_window"),
  key({ mod, "Shift" }, "space", "toggle_float_active"),
  key({ mod }, "space", "toggle_float_focus"),
  key({ mod, "Shift" }, "r", "way_cooler_restart"),

  -- Quitting way-cooler is hardcoded to Alt+Shift+Esc.
  -- If rebound, then this keybinding is cleared.
  key({ mod, "Shift" }, "escape", "way_cooler_quit"),T
}

-- Workspace bindings for the Programmer Dvorak keymap.
local numerics = {
  [0] = "asterisk",
  [1] = "parenleft",
  [2] = "parenright",
  [3] = "braceright",
  [4] = "plus",
  [5] = "braceleft",
  [6] = "bracketright",
  [7] = "bracketleft",
  [8] = "exclam",
  [9] = "equal",
}
for i, k in pairs(numerics) do
	table.insert(keys, key({ mod }, k, "switch_workspace_" .. i))
	table.insert(keys, key({ mod, "shift" }, k, "move_to_workspace_" .. i))
end

-- Register the keybindings.
for _, key in pairs(keys) do
    way_cooler.register_key(key)
end

-- Register the mod key to also be the mod key for mouse commands
way_cooler.register_mouse_modifier(mod)


-- Execute some code after Way Cooler is finished initializing
way_cooler.on_init = function()
  util.program.spawn_startup_programs()
end

--- Execute some code when Way Cooler restarts
way_cooler.on_restart = function()
  util.program.restart_startup_programs()
end

--- Execute some code when Way Cooler terminates
way_cooler.on_terminate = function()
  util.program.terminate_startup_programs()
end
```

### Debug log

```
$ way-cooler 2> wc.log
```

See file [wc.log](https://github.com/way-cooler/way-cooler/files/1735702/wc.log).

**Comment by Timidger** [comment]
Thank you for the detailed issue, I'm going to point to this whenever I need to give examples of a good report.

I _think_ I have experience the exact same thing on my setup. Just in case I have: does this only happen on one workspace (namely the first one)? If so, try switching to a different workspace on the same monitor without any windows in the first workspace (so that it is deleted, since workspaces are deleted when switched away and they have no windows on it) and then switch back and try again.

I've found that with init sometimes the first workspace doesn't size its contents correctly (probably a race condition somewhere).

**Comment by edubenetskiy** [comment]
I've tried switching to a different workspace with no windows in the first workspace, then switching back and creating a tabbed layout. Unfortunately, I experienced the same problem. It actually seems that in the case I have there is no difference which workspace you choose (I completed the same switch-there-and-back procedure with other workspaces) -- it does not render borders of the root-level container whichever workspace it is.

**Comment by Timidger** [comment]
Oh I don't know how I missed this:

```
    root_borders = false, -- Display borders in root containers by default
```

That should be `true`, then you get root borders

**Comment by edubenetskiy** [comment]
Yes, thank you, now the borders are displaying. Sorry for my oversight. But the first thing I noticed after logging in is that on the first workspace there are no borders until switching to another workspace and then back, i.e. the race condition you described previously actually holds. And may I ask you, is there a way to display root borders only for stacked and tabbed layouts just like in *i3wm*, as the caption 'Horizontal layout' seems for me a little redundant? Thanks.

**Comment by Timidger** [comment]
There's no way to currently make it so that it only works for tabbed / stacked.

I'm not accepting any changes right now that are not related to matching awesome, but I can walk you through how to write a personal patch to fix that on the gitter channel.
