### ISSUE TITLE
bind workspace to output

### ISSUE THREAD

**Issue by ookhoi** [way-cooler/way-cooler#497]
Is it possible to bind workspaces to an output?

If I connect an external monitor to my laptop, workspace 1 is assigned to the external monitor, and workspace 2-9 are assigned to the laptop. I would prefer most workspaces to be assigned to the external monitor. I can't seem to find an option to configure that in init.lua, nor can I find the subject touched in Issues.

I'm currently on 0.8.0 (nixos).

**Comment by Timidger** [comment]
It's not currently possible to do this at startup time. By default when switching to a workspace that doesn't exist it will use the current output to make the workspace (e.g exactly like i3).

In the future, we will be like Awesome. If this is still an issue, please re-open.

**Comment by ookhoi** [comment]
Oke thanks :-)
