### ISSUE TITLE
Way Cooler can't link to system Lua on Fedora

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#527]
Continuation of #526.

Way Cooler does not link to lua correctly on Fedora machines since it has a lua library that hides the version. 

This is an rlua issue, and the fix should be to use pkg-config to emit the correct linking flags at compile time probably via `build.rs`.

I took a look and couldn't find where the linking flags are emitted by rlua.

CCing @kyren.

**Comment by psychon** [comment]
> I took a look and couldn't find where the linking flags are emitted by rlua.

Found it! `src/ffi.rs` in rlua has `#[link(name = "lua5.3")]` on its `extern "C"`-block.
Now that is not an ideal place to mess with pkg-config or anything like that...

**Comment by Timidger** [comment]
Will be fixed when https://github.com/chucklefish/rlua/pull/79 is merged.

Thanks acrisci.
