### ISSUE TITLE
How to set up awesome lua libraries?

### ISSUE THREAD

**Issue by acrisci** [way-cooler/way-cooler#528]
Does way-cooler work with the awesome lua libraries? Can you show me how to set up the LUA_PATH so way-cooler can find them?

I'm getting this:

```
 INFO [awesome::lua] src/awesome/lua/mod.rs:30 Initializing lua... 
 INFO [awesome::lua] src/awesome/lua/mod.rs:54 Loading way-cooler libraries... 
 WARN [awesome::lua] src/awesome/lua/mod.rs:111 Could not find an init file in any path! 
 WARN [awesome::lua] src/awesome/lua/mod.rs:112 Defaulting to pre-compiled init.lua 
 ERROR [awesome::lua] src/awesome/lua/mod.rs:127 [string "init.lua <DEFAULT>"]:7: module 'gears' not found:
	no field package.preload['gears']
	no file '/usr/local/share/lua/5.3/gears.lua'
	no file '/usr/local/share/lua/5.3/gears/init.lua'
	no file '/usr/local/lib/lua/5.3/gears.lua'
	no file '/usr/local/lib/lua/5.3/gears/init.lua'
	no file './gears.lua'
	no file './gears/init.lua'
	no file '/home/tony/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share/awesome/lib/gears.lua'
	no file '/home/tony/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share/awesome/lib/gears/init.lua'
	no file '/usr/share/awesome/lib/gearsinit.lua'
	no file '/etc/xdg/awesome/gears.so'
	no file '/home/tony/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share/awesome/lib/gears.so'
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	[string "init.lua <DEFAULT>"]:7: in main chunk
```

**Comment by Timidger** [comment]
You should be able to install the `awesome` package and it should "just work".

It's possible the path is wrong though...[check out this function which defines the path](https://github.com/way-cooler/way-cooler/blob/18a75b9d345ac0bc675cf525973cb1223d7083fa/src/awesome/mod.rs#L61).

Generally it should be pretty easy to find. Simple find where your awesome libs actually are (a quick disk destroying `grep / gears &2>/dev/null` will find it) and see why it's not showing up in that nice list lua prints when Way Cooler crashes.

**Comment by psychon** [comment]
> Can you show me how to set up the LUA_PATH so way-cooler can find them?

I have awesome's source in `/home/psychon/projects/awesome`. I already ran `make` in there so that awesome is built in the `build/` subdirectory. I can run way-cooler with `LUA_PATH='/home/psychon/projects/awesome/build/lib/?/init.lua:/home/psychon/projects/awesome/build/lib/?.lua;;' cargo run` (but I do have lgi installed for Lua 5.3 on my system! The `;;` in there adds Lua's default search path and makes sure that lgi is found).

(Sigh, at least I can run it after patching out all the stuff that wants to use Xwayland in way-cooler)

**Comment by acrisci** [comment]
@psychon thanks this works:

```
LUA_PATH='/home/tony/projects/awesome/build/lib/?/init.lua;/home/tony/projects/awesome/build/lib/?.lua;;' cargo run
```

But now I get

```
 ERROR [awesome::lua] src/awesome/lua/mod.rs:127 /home/tony/projects/awesome/build/lib/gears/surface.lua:54: attempt to call a nil value (field 'pixbuf_to_surface')
stack traceback:
	[C]: in field 'pixbuf_to_surface'
	/home/tony/projects/awesome/build/lib/gears/surface.lua:54: in function 'gears.surface.load_uncached_silently'
	/home/tony/projects/awesome/build/lib/gears/surface.lua:95: in function </home/tony/projects/awesome/build/lib/gears/surface.lua:91>
	(...tail calls...)
	/home/tony/projects/awesome/build/lib/gears/wallpaper.lua:204: in function 'gears.wallpaper.maximized'
	[string "init.lua <DEFAULT>"]:187: in upvalue 'set_wallpaper'
	[string "init.lua <DEFAULT>"]:197: in local 'func'
	/home/tony/projects/awesome/build/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	[string "init.lua <DEFAULT>"]:195: in main chunk
```

Which is probably a separate issue.

**Comment by Timidger** [comment]
Yes that looks to be a separate issue. Gonna go ahead and close this.

**Comment by psychon** [comment]
> attempt to call a nil value (field 'pixbuf_to_surface')

Heh, awesome changed its API. Commit ee944f4da8342187c2244edb01b90c54567129c4 added a new `awesome.pixbuf_to_surface` API. Before that there was only `awesome.load_image`.
It should be easy to add this new API to way-cooler: It just does what `load_image` does, minus the first `Pixbuf::new_from_file` (instead, the pixbuf is given as an argument from Lua in the form of a light user datum; no ownership is transferred).
