### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by SolarAquarion** [way-cooler/way-cooler#536]
= note: /home/solaraquarion/build/way-cooler-git/src/way-cooler-git/target/release/deps/libwlroots_sys-a3bd493bc9487101.rlib(xwm.c.o): In function `xwm_handle_xcb_error':
          /home/solaraquarion/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-7927524347d6987b/out/../../../../../wlroots-rs/wlroots-sys/wlroots/xwayland/xwm.c:1072: undefined reference to `xcb_errors_get_name_for_major_code'
          /home/solaraquarion/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-7927524347d6987b/out/../../../../../wlroots-rs/wlroots-sys/wlroots/xwayland/xwm.c:1080: undefined reference to `xcb_errors_get_name_for_minor_code'
          /home/solaraquarion/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-7927524347d6987b/out/../../../../../wlroots-rs/wlroots-sys/wlroots/xwayland/xwm.c:1085: undefined reference to `xcb_errors_get_name_for_error'
          /home/solaraquarion/build/way-cooler-git/src/way-cooler-git/target/release/deps/libwlroots_sys-a3bd493bc9487101.rlib(xwm.c.o): In function `xwm_handle_unhandled_event':
          /home/solaraquarion/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-7927524347d6987b/out/../../../../../wlroots-rs/wlroots-sys/wlroots/xwayland/xwm.c:1111: undefined reference to `xcb_errors_get_name_for_xcb_event'
          /home/solaraquarion/build/way-cooler-git/src/way-cooler-git/target/release/deps/libwlroots_sys-a3bd493bc9487101.rlib(xwm.c.o): In function `xwm_destroy':
          /home/solaraquarion/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-7927524347d6987b/out/../../../../../wlroots-rs/wlroots-sys/wlroots/xwayland/xwm.c:1295: undefined reference to `xcb_errors_context_free'
          /home/solaraquarion/build/way-cooler-git/src/way-cooler-git/target/release/deps/libwlroots_sys-a3bd493bc9487101.rlib(xwm.c.o): In function `xwm_create':
          /home/solaraquarion/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-7927524347d6987b/out/../../../../../wlroots-rs/wlroots-sys/wlroots/xwayland/xwm.c:1535: undefined reference to `xcb_errors_context_new'
          collect2: error: ld returned 1 exit status

**Comment by Timidger** [comment]
Please install the wlroots dependencies (specifically the xcb and xwm ones it looks like)

**Comment by SolarAquarion** [comment]
I have wlroots installed on my system though

On Tue, May 22, 2018 at 2:19 PM, Preston Carpenter <notifications@github.com

**Comment by Timidger** [comment]
Wlroots is compiled statically by default. If you want to link to the library at runtime, disable the static flag on wlroots-rs dependency (in the Cargo.toml)
