### ISSUE TITLE
Using https on way-cooler.org

### ISSUE THREAD

**Issue by Eragonfr** [way-cooler/way-cooler#570]
If it's possible you should use https, with let's encrypt for example, on your site

**Comment by Timidger** [comment]
way-cooler.org uses github pages, so it cannot use https at this time. In the future if I switch to either be self hosting or another provider then I will use https.

For now though this isn't critical considering there's nothing sensitive on the website nor any information that you can actually submit to it. The binary installs are a slight issue, but ultimately that has been poorly supported by me historically and will just be removed for later versions.
