### ISSUE TITLE
Failed to compile, with no obvious error, but changes to 5 errors with `--verbose` flag on `cargo build`

### ISSUE THREAD

**Issue by lostinblue** [way-cooler/way-cooler#571]
Hello, 

I had several issues with building but eventually worked out all of the dependency issues but unfortunately, it is still failing to compile. And even worse, there is no obvious errors. There are warning near the end of the build process but no errors.

The after building or during `wlroot-rs`, the last warning is `awesome/src/main.rs:206:1`

Just ends with: "`error: build failed`"

I'm on Debian 9 (buster), using `rustup default beta` (tried `nightly` and `stable` too).

I have been using `cargo clean` to ensure the build environment doesn't have old stuff in it.

It passes a line that says "compiled awesome" so I thought that part was done already. It fails on "Compiling way-cooler v0.8.0"...

I tried running with `--verbose` which adds a line `Running 'rustc --crate name way_cooler way-cooler/src/main.rs --crate-type bin....`

Then `error[E0433]: failed to resolve. Did you mean nix::libc`

With verbose I also found: `error[E0425]: cannot find value 'L_DEBUG' in module 'wlroots::utils'`

and `error[E0308]: mismatched types` on output.rs:49

So with verbose is indicates 5 errors, but without  it there is literally no indication of any errors.

**Comment by lostinblue** [comment]
I definitely initialized the submodules after dowloading the repository.

**Comment by lostinblue** [comment]
There are only two submodules right? `wlroots-rs/wlroots-sys/wlroots` and `wlroots-rs`?

**Comment by psychon** [comment]
(Yup, only two submodules)
Well, I have Cargo & Rust 1.28.0 and can do
```
$ git clone https://github.com/way-cooler/way-cooler.git
$ cd way-cooler
$ git submodule update --init --recursive
$ cargo build
```
The build fails with a slightly unrelated error here (happens because Fedora calls the library `liblua5.3.so` instead of `liblua.so`)
```
[...]
  = note: /usr/bin/ld: cannot find -llua5.3
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `awesome`.
```

**Comment by lostinblue** [comment]
That is exactly what I did, but now I'm getting:

````
 linking with `cc` failed
````

I also did it under a fresh debian install.
