### ISSUE TITLE
Race condition with awesome part

### ISSUE THREAD

**Issue by AdminXVII** [way-cooler/way-cooler#588]
* Way Cooler version: commit 2a30f916e08aedf068457bb8c4c0a4590122e661 as well as 5782d0e5ac501708beb120dd049fa8db3b05531e (so it is not the latest update which is responsible)
* default
* Debug log
```
 INFO [awesome] awesome/src/main.rs:271 Logger initialized 
 TRACE [awesome::lua] awesome/src/lua/mod.rs:61 Setting up Lua libraries 
 INFO [awesome::lua] awesome/src/lua/mod.rs:36 Initializing lua... 
 INFO [awesome::lua::config] awesome/src/lua/config.rs:21 Loading way-cooler libraries... 
 INFO [awesome::lua::config] awesome/src/lua/config.rs:94 Found init file @ "/home/adminxvii/.config/way-cooler/rc.lua" 
 WARN [awesome::awesome] awesome/src/awesome.rs:338 xrdb_get_value not supported 
 INFO [awesome::lua::config] awesome/src/lua/config.rs:44 Read init.lua successfully 
 WARN [awesome::root] awesome/src/root.rs:89 Fake setting the wallpaper 
awesome: tpp.c:84: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
[1]    28656 abort (core dumped)  ./target/debug/awesome
```
It happens like one time each X (which points to a race condition).

[bt.gz](https://github.com/way-cooler/way-cooler/files/2536460/bt.gz)
So it is a free after free condition with wayland-client.

The message from the debug log however does not point the same way, so maybe this is in fact two race conditions?

# Bonus information
If you provide this information as well, I can respond to your request much faster:
* Is the issue reproducible on Sway? Did not test, but should not, as it is not the compositor part
* Is the issue reproducible on Awesome? Clearly not
* What distro do you run? Ubuntu server 18.04
* How did you install Way Cooler? Built from source

**Comment by Timidger** [comment]
I _think_ I ran into this issue before and fixed it in some as of yet unreleased commits that I worked on before I went on my hiatus.

My hiatus ends this week so I will soon be pushing much more code. I'll ping here once it's pushed if I haven't experienced it and we can see if I fixed it.

**Comment by Pablo1107** [comment]
Offtopic but why do you use Ubuntu server for development instead of regular Ubuntu or some other distro?

**Comment by AdminXVII** [comment]
Well Ubuntu Server is basically ubuntu without a DE preinstalled. Since I run basically only terms and firefox (Vim ftw) on awesome, I would need to remove all of it anyway. For the other distros, Debian is too stable, so I need to install basically everything from source or from ppa, Arch breaks sometimes and i dont want to fix it when I need to work (this happens in ubuntu too, but it is far less frequent) and I have not tried redhat's distros nor BSDs because ubuntu seems to suit my needs.

**Comment by Timidger** [comment]
I'm certainly not complaining. I use arch for the dev and build server so if there's any issues on other distros (mostly deps issues) I don't know about them.

I'm going to start worrying about that at 1.0, because we obviously need to focus on getting this ready before getting it stable / installable.

**Comment by Pablo1107** [comment]
Interesting. Didn't knew Ubuntu had a barebone version with no DE. I'm using Arch since 2 years now and I rarely encounter a big error I cannot fix with a few Google searches or downgrading a package if I need to.

**Comment by Timidger** [comment]
Once #591 is merged, can you confirm this isn't an issue?

**Comment by AdminXVII** [comment]
No crashes after 15 tries. Assuming it is fixed.
