### ISSUE TITLE
Core Feature: status bar

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#65]
A status bar is needed for Way Cooler. The design is still up in the air, and this will be updated when there is more information...

**Comment by DorianGray** [comment]
Maybe a lua API for managing events, like when a new window is added or whatever, and a default theme? I've done a ton of stuff with awesome in this space, including rendering my own vector icons using cairo from lua.

http://imgur.com/a/RGKm5

**Comment by Timidger** [comment]
I believe that's the route we are going. We are leaning towards using Conrod and Lua together, with a Conrod layer exposing a nice widget construction library/framework that Lua can call into and dynamically construct and modify the bar.

**Comment by DorianGray** [comment]
Neat! I read a little about that in another issue.

**Comment by myfreeweb** [comment]
I wrote [systemstat](https://github.com/myfreeweb/systemstat) + [unixbar](https://github.com/myfreeweb/unixbar) for dzen2/lemonbar/i3bar/swaybar… Actually a simple i3-compatible bar in way-cooler like in sway would be cool.

Also, you could use systemstat directly for getting system info in your bar. (Linux support is incomplete for now: loadavg/memory/battery works, cpu/mounts/networks aren't implemented.)

**Comment by Timidger** [comment]
The bars are designed to be swappable, so an i3-compatible bar could definitely be something that can be developed (either by us or others). The sway one won't work, since he makes sway-specific IPC calls in his. It could be translated easily enough to Rust/the IPC Way-Cooler though.

We'll look into using systemstat when we start work on the bar, we are still probably a month out at least from starting to work on that.

**Comment by SolidTux** [comment]
What are the current plans for this? I'd like to help with this issue, but I don't know where to start.

**Comment by Timidger** [comment]
Hi there!

The plan is for the status bar to be the same as in awesome, so really this issue is kind of useless now because there not be a dedicated bar program.
